### PR TITLE
Make CPU share scale with Memory

### PR DESCRIPTION
**Pull request by ddollar**
Should make CPU metric more meaningful

### CODE REVIEW

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;AT01A0No&#x2F;185-cpu-percentage-is-inaccurate"> CPU percentage is inaccurate</a>

**Comment by ddollar** [comment]
This reflects the same behavior AWS uses for Lambda.

**Comment by nzoschke** [comment]
http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html

The Task Definition CPU setting is fairly arbitrary on how it affects running containers. It is not required to set at all, and only guides soft guarantees in the kernel and cgroups about how a container runs. What happens in effect is that all running containers compete to use the CPU they need irregardless of what this might set.

So this patch only tweaks how we can account for CPU usage. Before this patch we were using a constant number for all container tasks. Now we set the number proportional to the memory, which is commonly scaled up or down.

**Comment by mattmanning** [comment]
:+1:

**Pull request merged**
