### PR TITLE
Code sync should respect .dockerignore

### LINKED ISSUE #766: convox start syncing should respect .dockerignore
This is already working on the host side, but needs to be applied [container side](https://github.com/convox/rack/blob/master/cmd/changes/main.go), too.

### PR DESCRIPTION
**Pull request by mattmanning**
Fixes #766 

This seems to be working right, but I would appreciate some extra testing.

### CODE REVIEW

**Comment by mattmanning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;i2c8JDoZ&#x2F;428-convox-sync-respects-dockerignore"> convox sync respects .dockerignore</a>

**Comment by ddollar** [comment]
Can we add some quick tests around this?

**Comment by awsmsrc** [comment]
@mattmanning what is the status of this one, happy to take it over if you're on other things

**Comment by mattmanning** [comment]
@awsmsrc I think it works. Looks good under manual testing, but I need to code some tests.

**Comment by mattmanning** [comment]
If I can't get to it by EOD today a handoff would be nice.

**Comment by ddollar** [comment]
This looks fine. Don't worry about the tests but let's clean up the commits.

**Comment by ddollar** [comment]
Please rebase this when you can. Does this make dockerignore work in both directions? (I saw an earlier comment that suggested it didn't)

**Pull request closed without merging**
