### PR TITLE
prune docker images from build instance

### PR DESCRIPTION
**Pull request by ddollar**

### CODE REVIEW

**Comment by mwarkentin** [comment]
Any thoughts on how to do this on the instances that the api containers run on? We find we have a bigger issue with those as it's 2 out of 45 instances that has the issue. Maybe just do the same thing on all of the cluster instances?

**Comment by ddollar** [comment]
You should not be seeing this issue on the instances the API containers run on unless you are running `docker build` manually there somehow. ECS cleans up after itself manually for all of the images it starts.

**Comment by ddollar** [comment]
Actually thinking more about it I can see how gen1 apps could cause this on the API container instances. I'm hesitant to add this to all instances for fear of interfering with the images the ECS agent expects to be there. Will need to do a bit more research toward that end.

**Comment by mwarkentin** [comment]
Yeah, the api containers do a docker pull on each deploy which doesn’t get cleaned up by the ECS agent. 

Fwiw our fix is to run docker prune —all —force (I think those are the options) on those instances. We haven’t seen any negative impact after doing that.

**Comment by advance512** [comment]
Will this help when using the overlay fs?

**Pull request closed without merging**
