### PR TITLE
Prevent kernel downtime during instance rolls

### PR DESCRIPTION
**Pull request by ddollar**

### CODE REVIEW

**Comment by nzoschke** [comment]
:+1:

**Comment by ddollar** [comment]
`20160202210501-resilient-kernel`

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;U7Qlwp9r&#x2F;277-prevent-rack-api-downtime-during-rolling-updates"> prevent rack api downtime during rolling updates</a>

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;T7LvBaWV&#x2F;314-pending-process-list-seems-inaccurate"> pending process list seems inaccurate</a>

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;mJYO8WNH&#x2F;323-use-deployment-options-to-roll-kernel-service-with-less-overhead"> use deployment options to roll kernel service with less overhead</a>

**Pull request merged**
