### PR TITLE
Update to the new equinox SDK for self-updates.

### PR DESCRIPTION
**Pull request by inconshreveable**
This switches the convox CLI over to use the new Equinox update SDK. There is a corresponding pull request for convox/release that switches the release process over to use the new release tool.

This pull request should be applied and published with the old equinox release mechanism *first*, before merging the pull request for convox/release. This ensures there is continuous update path that will always allow a user to get to the latest version of the CLI.

### CODE REVIEW

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;EUiGz57G&#x2F;219-move-cli-release-over-to-new-equinox"> move cli release over to new equinox</a>

**Comment by csquared** [comment]
@inconshreveable mind rebasing so we can merge this in?  i'd like to ship a CLI release tomorrow so happy to take this over if you're unable

**Comment by inconshreveable** [comment]
all set!

**Comment by csquared** [comment]
had to rebase myself over here: #164

**Pull request closed without merging**
