### PR TITLE
Monitor should get all ecs instances

### PR DESCRIPTION
**Pull request by beedub**
The previous code would pick up at most 100 instances in a cluster, so the monitor would kill instances erroneously. This change iterates through all instances.

### CODE REVIEW

**Comment by nzoschke** [comment]
The pagination LGTM. I can cut you a release of this for further testing...

**Comment by nzoschke** [comment]
In testing, this looks normal with a small number of instances:

```
$ convox rack logs --filter=monitor
2016-08-19T17:18:48Z web:20160819164214-20160819/0ff083a71eed ns=services_monitor fn=monitorConverged converged=true events=0 lastEventAt="2016-08-19 17:16:13 +0000 UTC"
2016-08-19T17:19:47Z web:20160819164214-20160819/0ff083a71eed ns=cluster_monitor tick
2016-08-19T17:19:48Z web:20160819164214-20160819/0ff083a71eed ns=cluster_monitor count=3 connected='i-05c92094,i-b59ba4bb,i-f847aa6b' healthy='i-05c92094,i-b59ba4bb,i-f847aa6b' marked=''
2016-08-19T17:19:48Z web:20160819164214-20160819/0ff083a71eed ns=services_monitor fn=monitorConverged converged=true events=0 lastEventAt="2016-08-19 17:16:13 +0000 UTC"
```

I'm testing with >100 instances next.

**Comment by nzoschke** [comment]
I tested the pagination locally with this patch:

```
diff --git a/api/workers/cluster.go b/api/workers/cluster.go
index 416cbcd..dfe4193 100644
--- a/api/workers/cluster.go
+++ b/api/workers/cluster.go
@@ -137,12 +137,11 @@ func (instances Instances) describeECS() error {
        for {
                res, err := models.ECS().ListContainerInstances(
                        &ecs.ListContainerInstancesInput{
-                               Cluster: aws.String(os.Getenv("CLUSTER")),
-                               NextToken: &nextToken,
-
+                               Cluster:    aws.String(os.Getenv("CLUSTER")),
+                               NextToken:  &nextToken,
+                               MaxResults: aws.Int64(2),
                        },
                )
```

It is correctly paginating and seeing 3 instances:

```
monitor  │ ns=cluster_monitor count=3 connected='i-05c92094,i-b59ba4bb,i-f847aa6b' healthy='i-05c92094,i-b59ba4bb,i-f847aa6b' marked=''
```

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;31SvyjjF&#x2F;521-100-instances-for-doordash"> 100+ Instances (for Doordash)</a>

**Pull request closed without merging**
