### PR TITLE
Scale to -1 to Disable ELB and Service

### LINKED ISSUE #472: Destroy ELB when process scaled to `0`
When my `docker-compose.yml` has a `redis` or `postgres` service defined, but I'm using an external service on convox, I scale that process to `0`, as I don't need those containers running.

However, the ELB which has been created for these processes sticks around, and costs me money (I believe $18/month/ELB).

The ELB should either be removed when I scale to `0`, or I should have some way of specifying that I want the ELB removed (option on `convox scale`?).

### PR DESCRIPTION
**Pull request by nzoschke**
Fixes #472. 

Preserves the behavior of scaling to 0 and retaining the ELB, as this is a useful maintenance mode procedure.

Enables scaling to -1 which explicitly deletes the ELB and ECS service. This is a destructive action, scaling back up to 0 or 1 will create a new ELB with a new hostname.

## Demo

```bash
# start with a single web process / ELB
$ convox scale
NAME  DESIRED  RUNNING  MEMORY
web   1        1        256   

$ convox ps
ID            NAME  RELEASE      SIZE  STARTED        COMMAND         
2ed3a4dcdc1e  web   RDJQJEUAPTP  256   2 minutes ago  httpd-foreground

$ convox apps info
Name       httpd
Status     running
Release    RDJQJEUAPTP
Processes  web
Endpoints  httpd-web-7E5UPCM-602527344.us-east-1.elb.amazonaws.com:80 (web)

$ curl httpd-web-7E5UPCM-602527344.us-east-1.elb.amazonaws.com
<html><body><h1>It works!</h1></body></html>

# scale to 0 stops the process but retains the ELB
$ convox scale web --count=0
NAME  DESIRED  RUNNING  MEMORY
web   0        1        256 

$ convox ps
ID  NAME  RELEASE  SIZE  STARTED  COMMAND

$ convox apps info
Name       httpd
Status     running
Release    RDJQJEUAPTP
Processes  web
Endpoints  httpd-web-7E5UPCM-602527344.us-east-1.elb.amazonaws.com:80 (web)

$ curl httpd-web-7E5UPCM-602527344.us-east-1.elb.amazonaws.com
curl: (52) Empty reply from server

# scale to -1 destroys the ELB
$ convox scale web --count=-1
NAME  DESIRED  RUNNING  MEMORY
web   -1       0        256 

$ convox ps
ID  NAME  RELEASE  SIZE  STARTED  COMMAND

$ convox apps info
Name       httpd
Status     running
Release    RDJQJEUAPTP
Processes  web
Endpoints  :80 (web)

# scale back to 1 creates a new process and ELB.
# The ELB has a new name and takes a while to resolve.
$ convox scale web --count=1
NAME  DESIRED  RUNNING  MEMORY
web   1        0        256 

$ convox ps
ID            NAME  RELEASE      SIZE  STARTED         COMMAND         
24634b23936d  web   RDJQJEUAPTP  256   22 seconds ago  httpd-foreground

$ convox apps info
Name       httpd
Status     running
Release    RDJQJEUAPTP
Processes  web
Endpoints  httpd-web-7E5UPCM-40044007.us-east-1.elb.amazonaws.com:80 (web)

$ curl httpd-web-7E5UPCM-40044007.us-east-1.elb.amazonaws.com
curl: (6) Could not resolve host: httpd-web-7E5UPCM-40044007.us-east-1.elb.amazonaws.com

$ curl httpd-web-7E5UPCM-40044007.us-east-1.elb.amazonaws.com
<html><body><h1>It works!</h1></body></html>

```

## Release Playbook
- [ ] Rebase against master
- [ ] Release branch ()
- [ ] Pass CI ()
- [ ] Code review
- [ ] Merge into master
- [ ] Release master ()
- [ ] Pass CI ()
- [ ] Update staging rack
- [ ] Edit [Rack release record](https://github.com/convox/rack/releases) and/or update [docs](https://github.com/convox/convox.github.io)
- [ ] Publish release
- [ ] Release CLI

### CODE REVIEW

**Comment by nzoschke** [comment]
When going from WebDesiredCount 0 to 1:

screen shot 2016-05-31 at 6 30 27 pm

**Comment by nzoschke** [comment]
When going from WebDesiredCount 1 to 0:

screen shot 2016-05-31 at 6 34 24 pm

**Comment by nzoschke** [comment]
CC @mwarkentin @beedub. This feels really good with 0 and -1 options!

**Comment by mwarkentin** [comment]
Woo, nice!

**Comment by beedub** [comment]
this is great, thx @nzoschke 

an aside, is it possible to specify the process count in `docker-compose.yml`?

**Comment by nzoschke** [comment]
It's not yet possible to specify count in docker-compose.yml. The label pattern could work here... `convox.scale=-1` Though there are some product design questions with this approach.

**Comment by nzoschke** [comment]
Released. A bugfix found in testing is on #721

**Pull request closed without merging**
