### PR TITLE
autoscale rack count

### PR DESCRIPTION
**Pull request by ddollar**
- [x] block process scaling beyond the size of a single instance

### CODE REVIEW

**Comment by ddollar** [comment]
todo:
- [ ] block process scaling beyond the size of a single instance

**Comment by mattmanning** [comment]
Looks good to me so far. :+1: pending some testing and scaling block item listed above.

**Comment by ddollar** [comment]
`20160218031713-autoscale-rack`

**Comment by ddollar** [comment]
```
$ convox rack update 20160218031713-autoscale-rack
$ convox rack params set Autoscale=yes
```

**Comment by ddollar** [comment]
```
$ convox rack update 20160219162421-autoscale-rack
$ convox rack params set Autoscale=yes
```

**Pull request merged**
