### PR TITLE
Convox Update Enhancements

### PR DESCRIPTION
**Pull request by nzoschke**
- https://github.com/convox/rack/pull/502 disable automatic updates of kernel* packages
- https://github.com/convox/rack/pull/497 Suspend scheduled actions during rack updates

## TODO

- [x] Document AMI / Kernel updates (https://github.com/convox/convox.github.io/pull/118)

## Release Playbook
- [x] Rebase against master
- [x] Pass checks
- [x] Release branch (20160405001058-update-tweaks)
- [x] Pass CI (https://circleci.com/gh/convox/rack/691#build-parameters)
- [x] Code review
- [ ] Merge into master
- [ ] Release master ()
- [ ] Pass CI ()
- [ ] Update dev and testing racks
- [ ] Publish release
- [ ] Release CLI

### CODE REVIEW

**Comment by alex** [comment]
Should this include some documentation on what users need to do to get kernel updates?

**Comment by nzoschke** [comment]
@alex good call, I'll write up a guide about AMI / Kernel update now, as that's mission critical management of a rack.

**Comment by mwarkentin** [comment]
I think kernel updates might require a reboot of the instance, which never happens during the initialization. I think this is what was causing issues with the sysdig agent installation.

**Comment by nzoschke** [comment]
Here's some documentation for review. It does include rebooting instances which in my testing right now was really fast to do and recover from.

https://github.com/convox/convox.github.io/pull/118

**Comment by nzoschke** [comment]
Docs are published. Always open to more feedback though. http://convox.com/docs/updating-convox/

**Pull request merged**
