### PR TITLE
RDS options

### PR DESCRIPTION
**Pull request by mattmanning**
This adds 5 new options to service creation. Currently the new options are only applied in the Postgres template. The options are:

* --size
* --instance-type
* --version
* --multi-az
* --encrypted

### CODE REVIEW

**Comment by mattmanning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;a2v0B9DY&#x2F;211-rds-postgres-options"> RDS Postgres Options</a>

**Comment by csquared** [comment]
I'm not a huge fan of how this makes every service (papertrail and redis right now) get these options. Is there a way to do store the service-specific config another way or did that prove really difficult?  

I'm thinking something like a `map[string]string` called config or even doing something with subtypes and embedded types?

**Comment by ddollar** [comment]
I second the map for config map here.

**Comment by nathany** [comment]
Supporting multi-az out of the box will be great. Thanks.

That is one parameter that is a boolean rather than a string. How well will `map[string]string` work for parameters of different types?

**Comment by csquared** [comment]
@nathany the parsing and validation will still need to happen, but can happen on the server side. you could imagine a `Validate()` method that builds up the proper RDS config struct and does the conversions from strings to the proper types, returning an error if any of the conversions fail. But that's really just one way in a sea of infinity so didn't want to get too prescriptive.

(Also, if we have that method, it means you can safely persist the service as strings b.c the conversion still works.  Another different way would be to make a struct for each service so that you don't need to re-convert, but once you've separated the notion of "conversion" and "validation" then what we're really saying is we care more about the validation then exactly how its achieved, and we definitely want to validate data *before* we store it)

**Comment by nathany** [comment]
Thanks for clarifying. In that case, a map is certainly simpler than many little structs.

**Pull request closed without merging**
