### PR TITLE
Enable ECR for Ireland (eu-west-1)

### PR DESCRIPTION
**Pull request by rcaught**
## Release Playbook
- [ ] Rebase against master
- [ ] Release branch ()
- [ ] Pass CI ()
- [ ] Code review
- [ ] Merge into master
- [ ] Release master ()
- [ ] Pass CI ()
- [ ] Update staging rack
- [ ] Edit [Rack release record](https://github.com/convox/rack/releases) and/or update [docs](https://github.com/convox/convox.github.io)
- [ ] Publish release
- [ ] Release CLI

Fixes convox/rack#500.

https://aws.amazon.com/about-aws/whats-new/2016/03/amazon-ec2-container-
registry-available-in-eu-ireland/

### CODE REVIEW

**Comment by nzoschke** [comment]
This looks like it'll work but I'd like some more time to test this before releasing since its critical path.

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;L3S1h9Zm&#x2F;219-ecr-in-us-west-2"> ECR in us-west-2</a>

**Comment by nzoschke** [comment]
Thanks! Going to start testing this now.

**Comment by nzoschke** [comment]
Closing in favor of #705. Thanks!!

**Pull request closed without merging**
