### PR TITLE
WIP: Allow multiple apps in convox start with --link

### PR DESCRIPTION
**Pull request by ddollar**
This PR is rebased on top of #648

```
$ cd foo && convox start
web: starting

$ convox start --name bar --link foo
worker: starting (with $FOO_WEB_HOST)

$ convox start --link foo --link bar
monitor: starting (with $FOO_WEB_HOST and $BAR_WORKER_HOST)
```

## Release Playbook
- [ ] Rebase against master
- [ ] Release branch ()
- [ ] Pass CI ()
- [ ] Code review
- [ ] Merge into master
- [ ] Release master ()
- [ ] Pass CI ()
- [ ] Update staging rack
- [ ] Edit [Rack release record](https://github.com/convox/rack/releases) and/or update [docs](https://github.com/convox/convox.github.io)
- [ ] Publish release
- [ ] Release CLI

### CODE REVIEW

**Comment by mwarkentin** [comment]
Took a quick read through - here are a few questions I had (maybe some more examples of how you'd actually interact with this would help):

* How do I make a request from my host too `foo` or `bar` app? Are those environment variables in the logs set on the host? What do their values look like?
* The actual linking looks like it would have to be done manually, and possibly in a specific order - I'm not sure how this would react to trying to link an app that's not currently running. My concern here is that devs work on subsets of our apps at once

### Dev 1

Working on: `a1`, `a2`, `a3`
Runs (?):

```
# shell1
cd a1 && convox start

# shell2
cd a2 && convox start --link a1

# shell3
cd a3 && convox start --link a1 --link a2
```

### Dev 2

Working on: `a1`, `a4`, `a5`, `a6`
Runs (?):

```
# shell1
cd a1 && convox start

# shell2
cd a4 && convox start --link a1

# shell3
cd a5 && convox start --link a1 --link a4

# shell4
cd a6 && convox start --link a1 --link a4 --link a5
```

This seems pretty complicated, manual, and error-prone - but I could be misunderstanding how it's meant to be used.

**Comment by ddollar** [comment]
Yes, you have the basics correct. Working on some of the apps some of the time is a complicated proposition. My suggestion would be to build a shell script that run the `convox start`s for you. Perhaps in different tmux windows or terminal tabs?

**Comment by ddollar** [comment]
Something like this:

```shell
#!/bin/bash

if [ -z $@ ]; then
  processes="all"
else
  processes=$@
fi

[ -z "$processes" ] && processes="all"

requested() {
  [[ "$processes" == "all" ]] && return 0
  for e in $processes; do [[ "$e" == "$1" ]] && return 0; done
  return 1
}

start() {
  app=$1
  shift
  args=$@

  requested $app && echo "starting $app: $args"
}

start bar
start baz
start foo --link bar --link baz
```

**Comment by ddollar** [comment]
Only one application is accessible on the host. This is a limitation of Docker for Mac.

Any application started with `--link` does not expose its ports to the host. They are only available internally to other applications to access by `--link`ing to them.

**Comment by mattmanning** [comment]
This is really cool. I worry that we're overloading the word "link" a little too much, but I can't think of a great alternative . . .

**Comment by ddollar** [comment]
Are there fairly standard setups when working on different things? Perhaps you can create shell scripts to encode these:

```shell
$ cat start-mode1.sh
#!/bin/bash
term-new-window() { ... }
term-new-tab() { ... }

term-new-window
term-new-tab "cd ~/src/a1 && convox start --internal"
term-new-tab "cd ~/src/a2 && convox start --internal --link a1"
term-new-tab "cd ~/src/a3 && convox start --internal --link a1 --link a2"
```

**Comment by mwarkentin** [comment]
Yeah, I don't really think that this is a workable solution for us - many of our apps have both web processes (need to be reachable from host) as well as rpc processes for inter-app communication (communicating between docker containers should work great).

With that said, I don't have any specific suggestions at this point - the best I've got right now is being able to specify a unique local port for dev (which gives us multi-app access from the host, fixes port conflicts) and specify a different port to be exposed on the ELB (which we want to be 443 for all of our apps so we can access over HTTPS without specifying a port in our dev/stage/production racks).

Perhaps that looks something like this in `docker-compose.yml`:

```yaml
web:
  build: .
  command: actions/web.sh
  environment:
    - DEVELOPMENT_MODE=true
    - WEB_CONCURRENCY=2
  labels:
    - convox.elb.port=443  # Replace 9001 with 443 on the ELB
    - convox.port.443.protocol=https
  ports:
    - 9001:80  # Unique port for local dev
  links:
    - redis
redis:
  image: convox/redis
  ports:
    - 9301
```

Looking at this some more, this actually looks like it could be a good solution for our apps rpc communication for local dev (which we haven't needed yet in the first two apps). Need to think on that some more - might not be an issue because we could use unique ports for those already (and I think communicate over the docker network with those ports), since we don't have the `443` requirement that we have for web traffic..

**Comment by ddollar** [comment]
What about something like:

```
$ convox start
$ curl https://localhost:443/

$ convox start --port-shift 10000`
$ curl https://localhost:10443/
```

**Comment by mwarkentin** [comment]
That could work... especially if we could encode that in our `docker-compose.yml` via label or similar...

**Comment by ddollar** [comment]
Probably a `.convox/shift` file

**Comment by ddollar** [comment]
Took a swing at that in #662

**Pull request closed without merging**
