### PR TITLE
run specific release

### LINKED ISSUE #409: Run one off commands on a specific release
It would be great to be able to specify a specific release id when running a one off command.

Ex. `convox run bash --release REZAALHGXHQ`

### PR DESCRIPTION
**Pull request by bowmande**
## Release Playbook
- [ ] Rebase against master
- [ ] Pass checks
- [ ] Release branch ()
- [ ] Pass CI ()
- [ ] Code review
- [ ] Merge into master
- [ ] Release master ()
- [ ] Pass CI ()
- [ ] Update dev and testing racks
- [ ] Publish release
- [ ] Release CLI

allow users to run a command on a container for a given release

This allows user to build a release, then run commands such as
migrations then promote the release

Resolve #409

### CODE REVIEW

**Comment by nzoschke** [comment]
:+1: Thanks! Going to close this and test and release it on https://github.com/convox/rack/pull/530

**Comment by nzoschke** [comment]
I noticed in testing that this is working well w.r.t the older release images, but not the environment.

In reviewing this patch, I now see that it's copying environment from the current TaskDefinition.

It should be possible to use the Release EnvironmentUrl to get the encrypted release environment from S3, decrypt it and use that for the run.

**Comment by bowmande** [comment]
Ok, Thanks, I'll update this!

**Comment by nzoschke** [comment]
Cool. I'm going to leave the existing commits in the release, we can patch on top of them in due time.

**Comment by snario** [comment]
I don't think this is working as expected, see below

```bash
$ convox run --detach --release RXOBADAUJUR frontend "webpack --progress --config webpack-prod.config.js"
Running `webpack --progress --config webpack-prod.config.jsa` on frontend... OK
```
```bash
$ convox ps
ID            NAME      RELEASE      SIZE  STARTED         COMMAND
f067a1c76125  frontend  RXOBADAUJUR  0     13 seconds ago  sh -c 'webpack --progress --config webpack-prod.config.js'
```

```bash
convox exec f067a1c76125 sh
/frontend # env
...
RELEASE=RZUUCAXHSZD
```

Shouldn't the `RELEASE` variable be the one specified by `--release`?

**Comment by nzoschke** [comment]
@snario your expectation is correct around the RELEASE value. 

Another patch is needed to correctly pick up the right environment for the specified release.

I do believe this is picking up the right docker images for the specified release. Did your test confirm that?

**Pull request closed without merging**
