### PR TITLE
Implement extra_hosts directive

### PR DESCRIPTION
**Pull request by awsmsrc**
This works locally for `start` however the extra hosts do not appear in the AWS task definition UI.

I think this could be a bug with the AWS UI

### CODE REVIEW

**Comment by awsmsrc** [comment]
fixes #933

**Comment by ddollar** [comment]
A few bits of cleanup on this PR:
* Should rework the "wip" commit etc to be real commits describing the changes.
* The changes to the fixtures that are unrelated to this PR should be in a separate PR
* Satisfy codecov and hound

To make this work on the AWS side you will need to implement `ExtraHosts` in the task definition creation function in api/cmd/formation/handler/ecs.go

**Comment by awsmsrc** [comment]
The fixtures changes are related to the PR as app.tmpl changed to include ExtraHosts

**Comment by ddollar** [comment]
Needs rebase and Hound

**Comment by ddollar** [comment]
Actually since these fixtures are no longer being used by anything can we just remove them from the PR. They make it really hard to see what's going on here.

**Comment by awsmsrc** [comment]
I can remove them, however they have been invaluable during refactorings as you can see that you aren't changing things and breaking things that are being sent to AWS.

If we remove them I might create a new PR with them back in, I do want to reinstate some automated testing around this

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;62FUqZ1w&#x2F;487-extrahosts-support"> ExtraHosts support</a>

**Comment by ddollar** [comment]
Needs a PR for the docs site "docker-compose-file"

**Comment by ddollar** [comment]
If you `rm -rf api/models/fixtures` the tests dont' fail so they can't be all that helpful during refactorings. We should reinstate the tests that use these fixtures but let's do it in a different PR.

**Comment by awsmsrc** [comment]
agreed

**Comment by ddollar** [comment]
OK, should be possible to take this branch and at least test the ExtraHosts stuff in the manifest tests now

**Pull request closed without merging**
