### PR TITLE
Allow Convox to be installed in us-east-2.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by frewsxcv** [comment]
It has ECS, Lambda, EC2. What else does it need?

**Comment by frewsxcv** [comment]
I get this error when I try `make templates`:

```
> make templates
go get -u github.com/jteeuwen/go-bindata/...
make -C api templates
go-bindata -nometadata -pkg=models -prefix=models -o=models/templates.go models/templates/...
make -C cmd templates
make -C convox templates
go-bindata -pkg=templates -modtime=1475420665 -prefix=templates -o=templates/templates.go -ignore=templates.go templates/...
make -C provider templates
make -C aws templates
go-bindata -nometadata -pkg=aws -o templates.go ./templates/...
make -C sync templates
xgo -targets linux/amd64 -out changed ../changes/cmd/changed
Checking docker installation...
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      linux/amd64
 Experimental: true

Checking for required docker image karalabe/xgo-latest... found.
Cross compiling ....
Building locally ....
Compiling for linux/amd64...
can't load package: package .: no buildable Go source files in /
2016/10/18 11:09:58 Failed to cross compile package: exit status 1.
make[1]: *** [templates] Error 1
make: *** [templates] Error 2
```

Feel free to just close this PR and make the changes in a different commit. I don't have much time to look into this any further.

**Comment by jtvhk** [comment]
+1 for support for the new Ohio region -- we're eager to start using it 👍

**Comment by frewsxcv** [comment]
https://github.com/convox/rack/pull/1339

**Pull request closed without merging**
