### PR TITLE
Default process memory to 128 instead of 256

### PR DESCRIPTION
**Pull request by anthonyrisinger**
See #471 for rationale. PR is pretty much just a search/replace.

## Release Playbook
- [x] Rebase against master
- [x] Pass checks
- [ ] Release branch ()
- [ ] Pass CI ()
- [ ] Code review
- [ ] Merge into master
- [ ] Release master ()
- [ ] Pass CI ()
- [ ] Update dev and testing racks
- [ ] Publish release
- [ ] Release CLI

### CODE REVIEW

**Comment by anthonyrisinger** [comment]
It's not immediately clear to me why this fails so I'll wait until I know it's something desired.

**Comment by nzoschke** [comment]
I guess you can't see the travis results? Its failing due to:

```
--- FAIL: TestManifestFixtures (0.05s)
	manifest_test.go:43: Unexpected results for multi_balancer:
		0210 -       "Default": "128",
		0211 +       "Default": "256",
		
		0254 -       "Default": "128",
		0255 +       "Default": "256",
```

The .json files in api/models/fixtures need to be updated.

**Comment by anthonyrisinger** [comment]
...you mean all these?

```bash
# grep -B1 128 api/models/fixtures/multi_balancer.json 
    "WebMemory": {
      "Default": "128",
--
    "WorkerMemory": {
      "Default": "128",
--
        "Handler": "lambda.external",
        "MemorySize": "128",

# git show --stat 
commit c1fbe91f9d9961ab66e259409f461a02c1161358
Author: C Anthony Risinger <anthonyrisinger@exosite.com>
Date:   Wed Mar 23 10:52:47 2016 -0500

    Default process memory to 128 instead of 256

 api/controllers/formation_test.go                      | 16 ++++++++--------
 api/models/fixtures/complex_environment.json           |  2 +-
 api/models/fixtures/multi_balancer.json                |  4 ++--
 api/models/fixtures/multi_balancer_unbound.json        |  4 ++--
 api/models/fixtures/web_external_internal.json         |  2 +-
 api/models/fixtures/web_external_internal_unbound.json |  2 +-
 api/models/fixtures/web_postgis.json                   |  4 ++--
 api/models/fixtures/web_postgis_internal.json          |  4 ++--
 api/models/fixtures/web_postgis_internal_unbound.json  |  4 ++--
 api/models/fixtures/web_postgis_unbound.json           |  4 ++--
 api/models/fixtures/web_redis.json                     |  4 ++--
 api/models/fixtures/web_redis_unbound.json             |  4 ++--
 api/models/fixtures/worker.json                        |  4 ++--
 api/models/fixtures/worker_unbound.json                |  4 ++--
 api/models/templates/app.tmpl                          |  2 +-
 test/aws_cycles.go                                     |  8 ++++----

# grep -R '[^0-9a-z]256' api/
#
```

It wasn't clear where that 256 was even coming from but I didn't look too much closer at the time.

**Comment by nzoschke** [comment]
Doh, `make templates` strikes again.

```
$ make -C api templates
go-bindata -pkg=models -prefix=models -o=models/templates.go models/templates/...
$ make test
```

And check in the resulting changes to api/templates.go.

See https://github.com/convox/rack/issues/486 for more info. We'll find a way to avoid this gotcha soon

**Comment by anthonyrisinger** [comment]
Ahh yep, that's got me a couple times now. Maybe the unit or CI tests can just verify all the embedded templates match those on disk.

**Comment by nzoschke** [comment]
Sorry this PR has stalled. I still think it makes a lot of sense but the concern is that too low of a memory setting could cause folks to have a bad time out of the box.

If there was more data about how Rails does with 128 vs 256 MB that'd help make a decision... cc @mattmanning

**Comment by ddollar** [comment]
Closing this for now. We're doing a lot with Rails, etc lately. Perhaps at some point we can revisit these numbers with the `mem_limit` stanza and default docker-compose.yml for various frameworks/languages. Thanks for submitting!

**Pull request closed without merging**
