### PR TITLE
do not delete build of active release

### PR DESCRIPTION
**Pull request by MiguelMoll**

### CODE REVIEW

**Comment by MiguelMoll** [comment]
[can't delete old builds, I may have found a bug](https://trello.com/c/RlvFMXeA/2535-cant-delete-old-builds-i-may-have-found-a-bug)

**Comment by mattmanning** [comment]
I'm stills seeing some weird behavior here:

```
$ convox builds -a httpd
ID           STATUS    RELEASE      STARTED         ELAPSED  DESC
BWCTUGHSTPK  complete  RZEPYGTARGU  14 minutes ago  5s
BOBCJJJWWLM  complete  RLFOTVWLVRF  19 minutes ago  30s
BIRIIFHNKCZ  complete  RGSWNWABZMV  2 days ago      20s
BQEQAEILRBU  complete  RDFAORECZVS  2 days ago      3s
BCPLHZSKPOM  complete  RJAVZCGDKXR  2 days ago      30s
BMAFLPDDCYP  complete  RLYLDUPSXYC  1 week ago      15s
BIWEPPGAYKN  complete  RLPMJZMKQAF  1 week ago      9s
BYOEUDRDRGQ  complete  RGMPHDJWISD  1 week ago      5s

$ convox builds delete BOBCJJJWWLM -a httpd
Deleting BOBCJJJWWLM... ERROR: no such release: RLYLDUPSXYC

$ convox builds -a httpd
ID           STATUS    RELEASE      STARTED         ELAPSED  DESC
BWCTUGHSTPK  complete  RZEPYGTARGU  15 minutes ago  5s
BOBCJJJWWLM  complete  RLFOTVWLVRF  20 minutes ago  30s
BIRIIFHNKCZ  complete  RGSWNWABZMV  2 days ago      20s
BQEQAEILRBU  complete  RDFAORECZVS  2 days ago      3s
BCPLHZSKPOM  complete  RJAVZCGDKXR  2 days ago      30s
BMAFLPDDCYP  complete  RLYLDUPSXYC  1 week ago      15s
BIWEPPGAYKN  complete  RLPMJZMKQAF  1 week ago      9s
BYOEUDRDRGQ  complete  RGMPHDJWISD  1 week ago      5s
```

**Comment by MiguelMoll** [comment]
Would you be able to show `convox releases` output before the delete step?

**Comment by mattmanning** [comment]
@MiguelMoll The problem seemed to be that `RLYLDUPSXYC` was the active release but had been deleted. Once I promoted a newer release this behavior went away.

And I was prevented from deleting the active release again:

```
$ convox builds delete BWCTUGHSTPK -a httpd
Deleting BWCTUGHSTPK... ERROR: cannot delete build of active release: BWCTUGHSTPK
```

So this actually looks good to me. Gonna approve.

**Pull request closed without merging**
