### PR TITLE
Add CF Resource metadata

### PR DESCRIPTION
**Pull request by ianmalott**
Add Description, Name, or Tags to CF Resources where possible.

Before this is released, https://github.com/convox/rack/pull/2005 should be released in a required release and https://github.com/convox/console/pull/927 should be deployed to Console.

### CODE REVIEW

**Comment by MiguelMoll** [comment]
Quick rebase please.

**Comment by ianmalott** [comment]
Rebased

**Comment by ddollar** [comment]
Looks like this needs rebase and is not passing CI

**Comment by ianmalott** [comment]
Rebased again. CI looks to be passing now.

**Comment by ianmalott** [comment]
Any other manual tests I can/should run beyond updating a Rack to use this?

**Comment by MiguelMoll** [comment]
Have you tried uninstalling a Rack? Usually permissions that create have a delete to go with it.

**Comment by ianmalott** [comment]
Tested some more and ran into the following in CF when updating from 20170216230221 to a custom release including the modified rack.json.

screen shot 2017-02-22 at 11 57 45 am

Not sure how to interpret that at the moment, but will do some more reading. Any thoughts from others would be appreciated.

**Comment by MiguelMoll** [comment]
Any details on why the `EncryptionKeyAlias` is needed?

**Pull request closed without merging**
