### PR TITLE
use instance private ip for SSH

### PR DESCRIPTION
**Pull request by csquared**
uses public ip in development

### CODE REVIEW

**Comment by csquared** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;W1Dnxi0O&#x2F;264-use-privateip-to-ssh-to-instances"> use PrivateIp to ssh to instances</a>

**Comment by ddollar** [comment]
:+1:

**Comment by mattmanning** [comment]
:+1:

**Comment by nzoschke** [comment]
:+1:

**Pull request merged**
