### PR TITLE
Validate ec2 instance type when scaling

### LINKED ISSUE #246: Validate rack scale instance type input
I issued this command:

```
$ convox rack scale --count 6 --type m4xlarge
Name     convox
Status   updating
Version  20160109003156-cloudwatch
Count    6
Type     m4xlarge
```

And was surprised to see the stack update failed: "The specified instance type m4xlarge is not valid"

That's because it was a typo, the correct instance size is "m4.xlarge"

### PR DESCRIPTION
**Pull request by MiguelMoll**
Resolves #246

### CODE REVIEW

**Comment by MiguelMoll** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;je5yHw5G&#x2F;483-validate-rack-scale-instance-type"> Validate rack scale instance type</a>

**Comment by ddollar** [comment]
Please rebase when you can

**Comment by awsmsrc** [comment]
:+1: I rebased and went ahead and tested manually

**Comment by ddollar** [comment]
Also could use some test coverage

**Comment by MiguelMoll** [comment]
Not totally convinced on the testing strategy but it's a start.

**Pull request closed without merging**
