### PR TITLE
docker-compose variable substitution

### LINKED ISSUE #993: docker-compose variable substitution
https://docs.docker.com/compose/compose-file/#/variable-substitution

Support for variable substitution in `docker-compose.yml` would allow flexibility at deploy time.

For example being able to specify a "tagged" image when pulling from Docker Hub -

```
# docker-compose.yml
app:
  image: $IMAGE_NAME
```

Note: this is different to build time variables in the Docker file itself - 
https://github.com/convox/rack/issues/156

### PR DESCRIPTION
**Pull request by awsmsrc**
fixes #993

### CODE REVIEW

**Comment by awsmsrc** [comment]
@MiguelMoll ready for a review

**Comment by MiguelMoll** [comment]
Thoughts on supporting `$VAR` as well (without the `{}`)?  Docker-compose supports both ways. Another option compose supports is `$$IGNORE_VAR`. That way you can refer to environment variables that you don't want processed.

As is, PR lgtm :+1:

**Comment by ddollar** [comment]
As Miguel suggests let's support both `$VAR` and `${VAR}` and ignore `$$VAR`, the same as docker-compose for these.

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ZDnJKMxa&#x2F;459-docker-compose-variable-subtitution"> docker-compose variable subtitution</a>

**Pull request closed without merging**
