### PR TITLE
check that the process has external ports not the whole app

### PR DESCRIPTION
**Pull request by ddollar**

### CODE REVIEW

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;yK0MvPiZ&#x2F;196-check-only-processes-that-have-external-ports-when-scaling-rack"> check only processes that have external ports when scaling rack</a>

**Comment by mattmanning** [comment]
:+1:

**Comment by csquared** [comment]
:+1:

**Comment by nzoschke** [comment]
:+1:

**Pull request merged**
