### PR TITLE
Add --wait to `releases promote` and `deploy`

### PR DESCRIPTION
**Pull request by ddollar**
```
$ convox releases promote RPJBPUCVHUQ -a httpd --wait
Promoting RPJBPUCVHUQ... UPDATING
Waiting for RPJBPUCVHUQ... OK
```

## Release Playbook
- [ ] Rebase against master
- [ ] Release branch ()
- [ ] Pass CI ()
- [ ] Code review
- [ ] Merge into master
- [ ] Release master ()
- [ ] Pass CI ()
- [ ] Update staging rack
- [ ] Edit [Rack release record](https://github.com/convox/rack/releases) and/or update [docs](https://github.com/convox/convox.github.io)
- [ ] Publish release
- [ ] Release CLI

### CODE REVIEW

**Comment by mwarkentin** [comment]
Does this wait until the containers are deployed and running on ECS, or just for the ECS deployment to be created?

**Comment by ddollar** [comment]
It checks the current process list to make sure all processes are running the new release.

https://github.com/convox/rack/pull/805/files#diff-42dc6b980db4020854ec4450ad9a5942R163

**Comment by MiguelMoll** [comment]
`convox env set` has a flag to promote. A wait flag should be added there as well.

**Comment by MiguelMoll** [comment]
Merged via #820

**Pull request closed without merging**
