### PR TITLE
stop handling old-style services

### PR DESCRIPTION
**Pull request by ddollar**

### CODE REVIEW

**Comment by ddollar** [comment]
[Service name conflicts with full stack name](https://trello.com/c/0KHDM4xv/1182-service-name-conflicts-with-full-stack-name)

**Comment by MiguelMoll** [comment]
Would old services have to be updated if this update is applied? Anything to document now that the "old" way is no longer supported?

**Comment by ddollar** [comment]
Yes, we'll need to add some documentation around the old services and/or Rack versions that apply.

**Comment by mwarkentin** [comment]
It might be an issue if "delete and recreate" is the solution here (eg. for RDS).

**Comment by skwp** [comment]
Is this going to affect any of our custom services like fluentd?

**Comment by mattmanning** [comment]
[Send out email notification about breaking changes for old-style services and self-hosted Docker registry](https://trello.com/c/OlcYuXhZ/1545-send-out-email-notification-about-breaking-changes-for-old-style-services-and-self-hosted-docker-registry)

**Pull request closed without merging**
