### PR TITLE
Fixes #161: Adds a `password` option to `convox install`

### LINKED ISSUE #161: Create a Convox rack with a defined password
Would it be possible to create a Convox rack with a pre-defined password, instead of a generated password on each installation? I have looked at the documentation and the trello board and have not found any mention on this.

This would make it a lot simpler to automate the creation of multiple racks (i.e. one per environment).

Regards,

### PR DESCRIPTION
**Pull request by mwarkentin**
## Release Playbook
- [ ] Rebase against master
- [ ] Pass checks
- [ ] Release branch ()
- [ ] Pass CI ()
- [ ] Code review
- [ ] Merge into master
- [ ] Release master ()
- [ ] Pass CI ()
- [ ] Update dev and testing racks
- [ ] Publish release
- [ ] Release CLI

Not really sure how to set up my environment to work / test this locally, so I'm winging it a little bit here.
I believe this should handle either `--password` or `ENV[PASSWORD]`, as per the ticket description.

### CODE REVIEW

**Comment by mwarkentin** [comment]
Looks like the way I did it actually injects a random password value into the help docs - not sure if this matters, or if I should default to `nil` and replace with a random password in that case:

```
mwarkentin@Michaels-MacBook-Pro-2 convox (master) $ ./convox install --help
convox install: install convox into an aws account

Usage:
  convox install [credentials.csv]

Options:
   ...
   --password "oMnlNCrMnOkVkphszjMNwaCELyVMiY"	custom password for rack [$PASSWORD]
   ...
```

**Comment by nzoschke** [comment]
Thanks!

I want to keep `convox install --help` static, so default to "" is preferred.

Then the Usage should say something like "custom API password. If not set the password is randomly generated.

Can you make that modification? Then I'll merge it.

You can test this locally by building a new CLI binary locally with the Go toolchain:

```
$ go install github.com/convox/rack/cmd/convox
$ convox install --help
convox install: install convox into an aws account

Usage:
  convox install [credentials.csv]

Options:
   --ami 					ID of the Amazon Machine Image to install
   --dedicated					create EC2 instances on dedicated hardware
   --instance-count "3"				number of EC2 instances
   --instance-type "t2.small"			type of EC2 instances
   --region "us-east-1"				aws region to install in [$AWS_REGION]
   --stack-name "convox"			name of the CloudFormation stack [$STACK_NAME]
   --development				create additional CloudFormation outputs to copy development .env file [$DEVELOPMENT]
   --key 					name of an SSH keypair to install on EC2 instances
   --email 					email address to receive project updates [$CONVOX_EMAIL]
   --password "ENYYKZzxqzyQvcKsJzSlOiIzmqhhLw"	custom password for rack [$PASSWORD]
   --version "latest"				release version in the format of '20150810161818', or 'latest' by default [$VERSION]
   --vpc-cidr "10.0.0.0/16"			The VPC CIDR block
   --subnet0-cidr "10.0.1.0/24"			Subnet 0 CIDR block
   --subnet1-cidr "10.0.2.0/24"			Subnet 1 CIDR block
   --subnet2-cidr "10.0.3.0/24"			Subnet 2 CIDR block
   --subnet-private0-cidr "10.0.4.0/24"		Private Subnet 0 CIDR block
   --subnet-private1-cidr "10.0.5.0/24"		Private Subnet 1 CIDR block
   --subnet-private2-cidr "10.0.6.0/24"		Private Subnet 2 CIDR block
   --private					Create private network resources
   --private-api				Put Rack API Load Balancer in private network. Implies --private
```

**Comment by mwarkentin** [comment]
@nzoschke Can do, thanks!

**Comment by nzoschke** [comment]
Merged in https://github.com/convox/rack/pull/455. Thanks!

**Pull request closed without merging**
