### PR TITLE
Set EnableDnsSupport and EnableDnsHostnames for rack VPC

### PR DESCRIPTION
**Pull request by xtfxme**
http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-dns.html

Allows host instances within the rack to have internal hostnames only resolvable
from within the VPC. The host uses an Amazon provided DNS server configured via
DHCP. Containers mount /etc/resolv.conf from the host giving them the same
resolution. This allows unrelated EC2 instances to join the VPC, such as a mail
server, under a common local name (eg. mail.internal) for service discovery or
to simplify some configuration.

### CODE REVIEW

**Comment by xtfxme** [comment]
This is also necessary to use private hosted zones with the VPC via Route53.

**Comment by xtfxme** [comment]
Any concerns here? My understanding is it does not actually affect the normal operations, just allows some DNS trickery.

**Comment by ddollar** [comment]
These are being covered in #318 thanks!

**Comment by xtfxme** [comment]
Perfect thanks!

**Pull request closed without merging**
