### PR TITLE
use links to bind proxy container

### PR DESCRIPTION
**Pull request by ddollar**
This allows the proxy container to connect to the container it's proxying for.

See also: convox/proxy#3

## Quick CLI Release Playbook
- [ ] Code review
- [ ] Merge into master
- [ ] Release CLI

### CODE REVIEW

**Comment by nzoschke** [comment]
👍

**Comment by nzoschke** [comment]
- [ ] merge https://github.com/convox/proxy/pull/3
- [ ] publish new convox/proxy image

**Comment by mwarkentin** [comment]
Actually, I might be seeing an issue - not sure if proxy related at this point. When I `convox start` with this branch, I'm able to make 1-2 requests to my app, and then requests just seem to hang there.

Wondering if there's an issue w/ proxy keeping a connection open that it's not supposed to or something, and exhausting my puma worker processes? Will try to debug further.

**Comment by ddollar** [comment]
Merging on #668

**Pull request closed without merging**
