### PR TITLE
encryption flag for `convox resources` for mysql and postgres

### PR DESCRIPTION
**Pull request by SonOfBytes**
Adds encryption flag to `convox resources` for mysql and postgres.  It updates the convox cmd and cloudformation stacks.  No tests.  Uses Default KMS.

Tested by hand and seems to do the right thing.

This is based on the work by @alex posted in this issue https://github.com/convox/rack/issues/1335

Also tracked here https://github.com/convox/rack/issues/1834

This uses the default KMS - should probably use the convox kms - how best to reference this in cloud formation and is this the right approach?  My feeling is that user custom KMS key should be added when there is a user need.

What would be the best way to test or should we leave the testing as is?

### CODE REVIEW

**Comment by MiguelMoll** [comment]
The Rack stack has a kms arn resource that we could use here if the user doesn't specify a key themselves. That would involve making API calls to get that information (`resourceFromStack()`) and setting the parameters accordingly.

The test I believe can stay the same.

**Comment by SonOfBytes** [comment]
stubbed out the use of convox kms key - not yet working properly - will pick up tomorrow

**Comment by SonOfBytes** [comment]
I believe this is pretty close.  It used the Convox Master KMS Key when `--encryption` added.  Tested with the following commands and validating in console the RDS instances created and the cloud formation stacks.

```
CREATE MYSQL

$ convox resources create mysql --instance-type=db.m4.large --database=testrackdevpdbe --name=testrack-dev-pdba --private --encryption
Creating testrack-dev-pdba (mysql: database="testrackdevpdbe" encryption="true" instance-type="db.m4.large" name="testrack-dev-pdba" private="true")... CREATING

$ convox resources create mysql --instance-type=db.m4.large --database=testrackdevpdbe --name=testrack-dev-pdbb --private
Creating testrack-dev-pdbb (mysql: database="testrackdevpdbe" instance-type="db.m4.large" name="testrack-dev-pdbb" private="true")... CREATING

CREATE POSTGRES

$ convox resources create postgres --instance-type=db.m4.large --database=testrackdevpdbe --name=testrack-dev-pdbc --private --encryption
Creating testrack-dev-pdbc (postgres: database="testrackdevpdbe" encryption="true" instance-type="db.m4.large" name="testrack-dev-pdbc" private="true")... CREATING

$ convox resources create postgres --instance-type=db.m4.large --database=testrackdevpdbe --name=testrack-dev-pdbd --private
Creating testrack-dev-pdbd (postgres: database="testrackdevpdbe" instance-type="db.m4.large" name="testrack-dev-pdbd" private="true")... CREATING

DELETE MYSQL

$ convox resources delete testrack-dev-pdba
Deleting testrack-dev-pdba... DELETING

$ convox resources delete testrack-dev-pdbb
Deleting testrack-dev-pdbb... DELETING

DELETE POSTGRES

$ convox resources delete testrack-dev-pdbc
Deleting testrack-dev-pdbc... DELETING

$ convox resources delete testrack-dev-pdbd
Deleting testrack-dev-pdbd... DELETING
```

The rack.json needed a couple of KMS permissions for when using KmsKeyId in creating RDS instanced through cloud formation.

Let me know if anything needs adjusting/refactoring.

**Comment by MiguelMoll** [comment]
[Review encryption flag for `convox resources` for mysql and postgres](https://trello.com/c/xE5kwDCs/2231-review-encryption-flag-for-convox-resources-for-mysql-and-postgres)

**Comment by MiguelMoll** [comment]
Carrying it forward via #2110. Thanks @SonOfBytes !

**Pull request closed without merging**
