### PR TITLE
Fix build ID completion

### PR DESCRIPTION
**Pull request by soulshake**
- Don't set `BASH_COMPLETION_DEBUG`
- respect `--app` and `-a` when completing build IDs
- general cleanup

### CODE REVIEW

**Comment by soulshake** [comment]
[Completion updates](https://trello.com/c/fiOp2P0Y/2226-completion-updates)

**Comment by ianmalott** [comment]
@soulshake I think this one is going to be tough for me to review just by looking at the diff. Is there anything in particular I should test out? How would I test the `BASH_COMPLETION_DEBUG` and `--app` and `-a` changes?

**Comment by soulshake** [comment]
@ianmalott you can test by comparing the auto-completed build IDs between different apps, e.g. `convox builds info --app APP1 <tab>` vs `convox builds info --app APP2 <tab>` and making sure the command works with the autocompleted build ID.

```
$ convox builds info --rack squirrels/legit --app cv-soulshake-net <TAB>
BAPCJQMUVZB  BBQIRZEGDMJ  BFDMKRLAMXV  BKBCVBKHVSJ  BKKJDNWXLXG  BLAFHALKWJP  BLIDZLBHUFG  BMGPBGRDXZN  BMXNNWANKWL  BOJSARXEOYH  BQLXJWUNXKX  BVDZJIQBAIE  BWAQTMPEUXX  BWHJWEXMWSS  BXNVGEJHXAH  BYQEDQDCZEL

$ convox builds info --rack squirrels/legit --app cv-soulshake-net BAPCJQMUVZB 
Build        BAPCJQMUVZB
Status       complete
Release      REBZZDWTCCB
Description  
Started      1 week ago
Elapsed      40s

$ convox builds info --rack squirrels/legit --app www-soulshake-net <TAB>
BBWAVUWXRTX  BDTVJXRGHSG  BNIHPPNAXYR  BQLQDOGSKRP  

$ convox builds info --rack squirrels/legit --app www-soulshake-net BBWAVUWXRTX 
Build        BBWAVUWXRTX
Status       complete
Release      RTURDPTYMXP
Description  Just testing app logs here
Started      6 days ago
Elapsed      1m28s
```

You can test `BASH_COMPLETION_DEBUG` by running `source convox` (`convox` being the name of this bash completion file) and making sure nothing appears at all on the screen (whereas if you have `BASH_COMPLETION_DEBUG` set to `true`, it will print all the commands that are being sourced).

**Comment by ianmalott** [comment]
I updated my bashrc to source the completion script, then restarted my terminal and got the following.

```
Sourcing /Users/ism/.bash_profile
Sourcing /Users/ism/.bashrc
-bash: /Users/ism/.dotfiles/bash/convox-completion: line 3311: syntax error in conditional expression: unexpected token `('
-bash: /Users/ism/.dotfiles/bash/convox-completion: line 3311: syntax error near `@($'
-bash: /Users/ism/.dotfiles/bash/convox-completion: line 3311: `        [[ ${words[$glob_pos]} == @($glob) ]] && echo "$key"'
```

I needed enable extended globbing before sourcing the script to prevent the error.

```
shopt -s extglob
```

It looks like completion works for the most part.
```
❯ convox
api         doctor      install     rack        scale       update
apps        env         instances   racks       services
build       exec        login       registries  ssl
builds      h           logs        releases    start
certs       help        proxy       resources   switch
deploy      init        ps          run         uninstall

❯ convox apps
cancel  create  delete  h       help    info    params

❯ convox start -
--file      --no-build  --no-cache  --no-sync   --shift     -f

❯ convox start --no-
--no-build  --no-cache  --no-sync
```

Testing the auto-completed build IDs didn't show differences between apps:

```
❯ convox apps
APP     STATUS
birdie  running
site    running

❯ convox builds info --app birdie <TAB>
--app       --rack      Commands:   Usage:      apps        builds      convox      deploy      env         help,       install     login       proxy       rack        registries  resources,  scale       start       uninstall
--help,     --version,  Options:    api         build       certs       convox:     doctor      exec        init        instances   logs        ps          racks       releases    run         ssl         switch      update

❯ convox builds info --app site <TAB>
--app       --rack      Commands:   Usage:      apps        builds      convox      deploy      env         help,       install     login       proxy       rack        registries  resources,  scale       start       uninstall
--help,     --version,  Options:    api         build       certs       convox:     doctor      exec        init        instances   logs        ps          racks       releases    run         ssl         switch      update

❯ convox builds info --rack personal/development --app birdie <TAB>
--app       --rack      Commands:   Usage:      apps        builds      convox      deploy      env         help,       install     login       proxy       rack        registries  resources,  scale       start       uninstall
--help,     --version,  Options:    api         build       certs       convox:     doctor      exec        init        instances   logs        ps          racks       releases    run         ssl         switch      update

❯ convox builds info --rack personal/development --app site <TAB>
--app       --rack      Commands:   Usage:      apps        builds      convox      deploy      env         help,       install     login       proxy       rack        registries  resources,  scale       start       uninstall
--help,     --version,  Options:    api         build       certs       convox:     doctor      exec        init        instances   logs        ps          racks       releases    run         ssl         switch      update
```

Should I need to change any other config to get the build ID completion working?

**Comment by ianmalott** [comment]
I also don't see the `BASH_COMPLETION_DEBUG` env var working as expected.

```
ism@murky ~
❯ BASH_COMPLETION_DEBUG=true source ~/.dotfiles/bash/convox-completion

ism@murky ~
❯
```

**Pull request closed without merging**
