### PR TITLE
Agent lambda fixes

### PR DESCRIPTION
**Pull request by spencerhakim**
- Fixes an error accessing `undefined`
- Listens for task state changes (for when containers exit unexpectedly)
- Cleaned up/improved some of the logic

### CODE REVIEW

**Comment by spencerhakim** [comment]
@nzoschke I've been running this on my rack for the last couple of days without issue. Up for a quick review?

**Comment by nzoschke** [comment]
@spencerhakim awesome, i'll take a look at this shortly

**Comment by nzoschke** [comment]
Thanks for your patience on this @spencerhakim. Code looks good to me. I'll help test and release this from here.

**Comment by MiguelMoll** [comment]
@spencerhakim When you get a chance, could you rebase on master?

**Comment by spencerhakim** [comment]
@MiguelMoll @nzoschke Done. Sorry if it seems like I haven't been paying much attention to this, was travelling all last week and the beginning of this week.

**Comment by MiguelMoll** [comment]
Moving forward via #2118.

**Pull request closed without merging**
