### PR TITLE
use aws cli to generate credentials if available

### PR DESCRIPTION
**Pull request by ddollar**
if the aws cli is installed and configured this will now try to read the credentials from your current profile if you haven't specified any as flags

### CODE REVIEW

**Comment by mwarkentin** [comment]
If you do end up doing something like this, we need to be able to pass the `--profile` option to our AWS CLI to specify the AWS account to be used (we have separate prod / dev accounts).

**Comment by ddollar** [comment]
@mwarkentin you can also set the `AWS_DEFAULT_PROFILE` environment variable to change the current default

**Comment by mwarkentin** [comment]
Oh true, that'd work. 👍

**Comment by mwarkentin** [comment]
@ddollar Just realized something similar for `convox uninstall` might be useful as well? Easy to port there as well?

**Pull request merged**
