### PR TITLE
Custom IAM roles for app Tasks

### PR DESCRIPTION
**Pull request by mattmanning**
This PR adds a TaskRole parameter to apps. If you want to set a custom IAM role to your ECS Tasks for the application you can run:

`convox apps params set TaskRole=myRole`

"myRole" can be either the ARN or the short name of the role.

### CODE REVIEW

**Comment by mwarkentin** [comment]
@mattmanning Nice - thoughts on providing a default role that could be used without any extra settings for an app?

**Comment by mattmanning** [comment]
[Custom IAM roles for ECS Tasks](https://trello.com/c/otePllNA/1588-custom-iam-roles-for-ecs-tasks)

**Comment by mattmanning** [comment]
[Custom IAM roles for ECS Tasks](https://trello.com/c/P2lIJCHL/378-custom-iam-roles-for-ecs-tasks)

**Comment by mattmanning** [comment]
@mwarkentin Not sure if that will make it into this change, but we will look into it.

**Pull request closed without merging**
