### PR TITLE
use 200GB volumes by default

### PR DESCRIPTION
**Pull request by csquared**

### CODE REVIEW

**Comment by csquared** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Ukj2dnLQ&#x2F;224-bigger-ebs-disks-on-cluster-instances"> Bigger EBS Disks on Cluster Instances</a>

**Comment by csquared** [comment]
```
~/go/src/github.com/convox/rack (larger-ebs)$ cx exec -a convox 96ff69349243 sh
/go/src/github.com/convox/rack # df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/mapper/docker-202:1-1048901-369b1535fb2c9f38e6df11ba634eebe9ed8da22fa3a7009c9e2e8c7aba3d1db1
                          9.7G    426.8M      8.8G   5% /
tmpfs                    15.0G         0     15.0G   0% /dev
shm                      64.0M         0     64.0M   0% /dev/shm
/dev/xvda1              196.7G      8.3G    188.1G   4% /var/run/docker.sock
/dev/xvda1              196.7G      8.3G    188.1G   4% /etc/resolv.conf
/dev/xvda1              196.7G      8.3G    188.1G   4% /etc/hostname
/dev/xvda1              196.7G      8.3G    188.1G   4% /etc/hosts
tmpfs                    15.0G         0     15.0G   0% /proc/kcore
tmpfs                    15.0G         0     15.0G   0% /proc/latency_stats
tmpfs                    15.0G         0     15.0G   0% /proc/timer_stats
/go/src/github.com/convox/rack # exit

```

**Comment by csquared** [comment]
of note, this already is a larger disk type

$ cx rack
Name     convox
Status   running
Version  20151124201423-larger-ebs
Count    3
Type     i2.xlarge

**Comment by nzoschke** [comment]
Some questions:

- [ ] What is the impact to Rack costs?
- [ ] What is the impact to instance boot time?
- [ ] Does this work with both EBS and SSD backed instances?

**Comment by tysontate** [comment]
@csquared Is this configurable by end-users?

**Comment by csquared** [comment]
Yes! You can just set the VolumeSize parameter on the convox stack

**Comment by tysontate** [comment]
@csquared Will any changes to `VolumeSize` get overwritten by the next `convox rack update`?

**Pull request merged**
