### PR TITLE
vendor compiled cfssl binary

### LINKED ISSUE #374: `convox ssl create` failing on cert chain resolution
The error looks like this:

```
$ convox ssl create web:443 ~/Downloads/www_feedchirp_com.crt ~/Downloads/www_feedchirp_com.key -a feedchirp
Creating SSL listener web:443... ERROR: could not generate chain: unexpected end of JSON input
```

I think the error is originating from the `resolveCertificateChain` method, but I haven't been able to figure out why.

Based on customer feedback this seems to have broken somewhere between the `20160213224638` and `20160221015019` releases.

### PR DESCRIPTION
**Pull request by ddollar**
fixes #374

### CODE REVIEW

**Comment by ddollar** [comment]
## Release Playbook
- [x] Rebase against master
- [ ] Pass checks
- [ ] Code review
- [ ] Release branch (20160223035816-compose-env)
- [ ] Pass CI ()
- [ ] Merge into master
- [ ] Release master
- [ ] Pass CI
- [ ] Update dev and testing racks
- [ ] If rack or app formation changes, test upgrade → re-deploy existing app → downgrade cycle
- [ ] Publish release
- [ ] Release CLI

**Comment by mattmanning** [comment]
:+1: Fix looks good. It would be nice to get some unit tests around this when we can.

**Comment by ddollar** [comment]
Not sure if unit tests would have caught this but we definitely need to exercise SSL in CI.

**Comment by nzoschke** [comment]
Huge +1 for CI around it. In fact I'd like to include that in this PR if possible. I can add it to the httpd test easy enough if nobody beats me to it.

**Pull request merged**
