### PR TITLE
[RELEASE] 20170118

### PR DESCRIPTION
**Pull request by ddollar**
## Pull Requests
  - closes #1535 UDP support + Disable ELB creation [@spencerhakim]
  - closes #1566 Use .NoError() instead of .Nil() for error checking in tests [@spencerhakim]

## Milestone Release
- [ ] Release branch
- [ ] Pass CI
- [ ] Code review
- [ ] Merge into master
- [ ] Close milestone
- [ ] Release master
- [ ] Record release number: 
- [ ] Pass CI
- [ ] Update demo
- [ ] Deploy demo/httpd
- [ ] Deploy demo/rails
- [ ] Update staging
- [ ] Deploy staging/site-staging
- [ ] Deploy staging/console-staging
- [ ] Update [release notes](https://github.com/convox/rack/releases)
- [ ] Documentation review
- [ ] Publish release
- [ ] Release CLI

### CODE REVIEW

**Comment by spencerhakim** [comment]
Hmm, not sure why I didn't have this problem when I tried installing to my own dev rack, though the process around that is... complicated. [This](https://github.com/convox/rack/blob/20170118/provider/aws/dist/rack.json#L1979) should've been changed to `4001:4443/tcp`.

**Comment by ddollar** [comment]
Yeah looks like this one happened in the Lambda function so you probably weren't seeing it locally unless you updated the CustomTopic Lambda function for your dev rack.

... Complicated indeed.

**Comment by spencerhakim** [comment]
This is making me wonder if I should've made the regex used [here](https://github.com/convox/rack/blob/20170118/provider/aws/lambda/formation/handler/ecs.go#L22) identical to the more lenient regex I used [here](https://github.com/convox/rack/blob/20170118/manifest/yaml.go#L13). I didn't think backwards compatibility would be an issue, yet here we are.

**Comment by MiguelMoll** [comment]
Going to put this release on hold for now. These changes should go out in the next release.

@spencerhakim Anything left to sort out with the regex? Complicated but awesome changes. 👍

**Comment by spencerhakim** [comment]
@MiguelMoll Would you like me to quickly throw these changes into another PR? Wasn't sure if you guys were planning on making the changes yourselves directly on this branch.

**Pull request closed without merging**
