### PR TITLE
Go 1.6 and vendor/

### PR DESCRIPTION
**Pull request by nzoschke**
- Use `golang:1.6-alpine` base image for official alpine + go 1.6 support ([Dockerfile](https://github.com/docker-library/golang/blob/0f3ab4a3d2eba38991ab7b41941f1dc99f13dc3f/1.6/alpine/Dockerfile))
- Upgrade to Go 1.6 for faster builds and native vendor/ support
- Get off Godeps :fire:
- Use https://github.com/bmizerany/vendor to copy things into vendor/ :hammer: 
- Update go-dockerclient and testify to fix some possible Godeps muckups
- Update travis and circle configs to 1.6

This goes with https://github.com/convox/release/pull/12 Build with Go 1.6. Before we can release this through the normal checklist we need to:

- [x] review alpine version
- [x] Resolve `Error response from daemon: client is newer than server (client API version: 1.22, server API version: 1.21)`
- [ ] Review, merge and deploy convox/release

I've been testing with convox/release in development with:

```
$ cd convox/release
$ git checkout go16
$ make build
$ docker run --env-file=.env -v /var/run/docker.sock:/var/run/docker.sock convox/release create go
```

### CODE REVIEW

**Comment by nzoschke** [comment]
@ddollar I'd like to pair up with you for review / release of this at your next convenience... Maybe first thing tomorrow?

**Comment by nzoschke** [comment]
```bash
$ go version
go version go1.5.3 linux/amd64

$ time go install -a -v ./...
real	0m 15.03s
user	0m 13.26s
sys	0m 0.63s
```

**Comment by nzoschke** [comment]
On alpine:edge

```
# docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   a5815f5
 Built:        Sun Mar 20 12:28:44 UTC 2016
 OS/Arch:      linux/amd64
```

alpine:3.3

``
# docker -v
Docker version 1.9.1, build e463610
/go/src/github.com/convox/rack # docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   e463610
 Built:        Tue Dec  1 18:05:05 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by ddollar** [comment]
Let's use the latest `godep` in vendor mode rather than bmiz/vendor. The new Godep still stores the SHAs which is important for being able to reconstruct GOPATH when updating packages or adding siblings.

Example:

* Developer A vendors `github.com/foo/bar/baz` at SHA 123456, commits, and pushes
* Developer B wants to vendor `github.com/foo/bar/qux` but doesn't know which SHA its sibling was committed using unless there is some sort of manifest.

This scenario will happen quite often with things like aws-sdk-go when we start using a new service.

**Comment by nzoschke** [comment]
@ddollar dang, was hoping to rage quit Godeps. But that makes sense for sufficiently complex dependencies like rack has

**Comment by nzoschke** [comment]
Closing this in favor of https://github.com/convox/rack/pull/539. Thanks for the review / feedback / pairing y'all.

**Pull request closed without merging**
