### PR TITLE
Change to use SSM to pull up-to-date AMI's and other information auto…

### PR DESCRIPTION
**Pull request by beastawakens**
…matically.  Adds support for CN regions

### CODE REVIEW

**Comment by fk-currenxie** [comment]
@beastawakens I see some mentions of ARM and t4g instances. Will that be supported? Will the rack Docker image targeting ARM be part of this as well?

**Comment by beastawakens** [comment]
> @beastawakens I see some mentions of ARM and t4g instances. Will that be supported? Will the rack Docker image targeting ARM be part of this as well?

@fk-currenxie This is beginning to introduce support for those instance types yes.  The Rack image running on ARM won't be part of this PR but is still on the roadmap 😊

**Comment by Twsouza** [comment]
In the current state, once the rack is installed, we can't update the AMI version. We need to be able to update the AMI version after instalation.

**Comment by Twsouza** [comment]
Done by https://github.com/convox/rack/pull/3553

**Pull request closed without merging**
