### PR TITLE
remove version check on rack api

### PR DESCRIPTION
**Pull request by ddollar**
This removes the required `Version` header requirement on the Rack API.

### CODE REVIEW

**Comment by MiguelMoll** [comment]
Is there a reason to not want to check a min version?

**Comment by mwarkentin** [comment]
@MiguelMoll Was there an answer to your question above? Do we need to worry about older-than-expected clients causing issues after this change?

**Comment by ddollar** [comment]
We are addressing deprecation at the API level (403 errors that tell you to upgrade your client when you try to use something that no longer exists)

**Comment by mwarkentin** [comment]
@ddollar Perfect, thanks!

**Pull request closed without merging**
