### PR TITLE
Local linking working with Docker for Mac

### PR DESCRIPTION
**Pull request by ddollar**
## Release Playbook
- [x] Rebase against master
- [ ] Release CLI
- [ ] Edit [Rack release record](https://github.com/convox/rack/releases) and/or update [docs](https://github.com/convox/convox.github.io)

### CODE REVIEW

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;KvCZSCTJ&#x2F;124-convox-start-docker-for-mac"> convox start docker for mac</a>

**Comment by nzoschke** [comment]
Testing this with Docker 1.11.1-beta10 now

**Comment by nzoschke** [comment]
I'm seeing this error more and more. Restarting Docker For Mac fixes it.

```
web    | docker: Error response from daemon: driver failed programming external connectivity on endpoint console-staging-web (f0e1206c85c1a0a8a69d3b22d247b99b0ace5b6bd965cd2aab6fecdc4eff7352): Error starting userland proxy: Failed to bind: EADDRINUSE.
```

**Comment by nzoschke** [comment]
Something is not working with the node-workers example app. It starts:

```
$ convox start
RUNNING: docker build -t convox-qurxhmagta -f /Users/noah/dev/node-workers/Dockerfile /Users/noah/dev/node-workers/
Sending build context to Docker daemon  72.7 kB
Step 1 : FROM node:argon
Step 2 : RUN mkdir -p /usr/src/app
Step 3 : WORKDIR /usr/src/app
Step 4 : COPY package.json /usr/src/app/
Step 5 : RUN npm install
Step 6 : COPY . /usr/src/app
Step 7 : EXPOSE 8080
Step 8 : CMD npm start
Successfully built b7633bde09d5

RUNNING: docker tag -f convox/redis node-workers/redis
Warning: '-f' is deprecated, it will be removed soon. See usage.
RUNNING: docker tag -f convox-qurxhmagta node-workers/web
Warning: '-f' is deprecated, it will be removed soon. See usage.
RUNNING: docker tag -f convox-qurxhmagta node-workers/worker
Warning: '-f' is deprecated, it will be removed soon. See usage.
redis  | docker run -i --name node-workers-redis -p 6379:6379 node-workers/redis
worker | docker run -i --name node-workers-worker -e REDIS_HOST=node-workers-redis -e REDIS_PASSWORD=password -e REDIS_PATH=/0 -e REDIS_PORT=6379 -e REDIS_SCHEME=redis -e REDIS_URL=redis://:password@node-workers-redis:6379/0 -e REDIS_USERNAME= --add-host=node-workers-redis:172.17.0.2 node-workers/worker sh -c node worker.js
redis  |                 _._                                                  
redis  |            _.-``__ ''-._                                             
redis  |       _.-``    `.  `_.  ''-._           Redis 3.0.5 (b1116499/0) 64 bit
redis  |   .-`` .-```.  ```\/    _.,_ ''-._                                   
redis  |  (    '      ,       .-`  | `,    )     Running in standalone mode
redis  |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis  |  |    `-._   `._    /     _.-'    |     PID: 1
redis  |   `-._    `-._  `-./  _.-'    _.-'                                   
redis  |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis  |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
redis  |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis  |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis  |  |    `-._`-._        _.-'_.-'    |                                  
redis  |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis  |       `-._    `-.__.-'    _.-'                                       
redis  |           `-._        _.-'                                           
redis  |               `-.__.-'                                               
redis  | 
redis  | 1:M 04 May 17:19:56.554 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis  | 1:M 04 May 17:19:56.554 # Server started, Redis version 3.0.5
redis  | 1:M 04 May 17:19:56.555 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis  | 1:M 04 May 17:19:56.555 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis  | 1:M 04 May 17:19:56.555 * The server is now ready to accept connections on port 6379
```

But the web process isn't running:

```
$ docker ps
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                    NAMES
110f2382e427        node-workers/worker   "sh -c 'node worker.j"   3 minutes ago       Up 3 minutes        8080/tcp                 node-workers-worker
4bd66c6b1302        node-workers/redis    "/docker-entrypoint.s"   3 minutes ago       Up 3 minutes        0.0.0.0:6379->6379/tcp   node-workers-redis
```

investigating...

**Comment by nzoschke** [comment]
When I ctrl-c and do it again it works. So I think this is generally correct. I'm still investigating what happened

**Comment by nzoschke** [comment]
It appears to be a race condition. On different runs I also got redis up but no web/worker. I'll investigate getting the order correct.

**Comment by nzoschke** [comment]
Seems to be something in the run order and timing. Removing the sleep results in only redis starting very consistently.

```
diff --git a/api/manifest/manifest.go b/api/manifest/manifest.go
index 32b2c24..045ddcd 100644
--- a/api/manifest/manifest.go
+++ b/api/manifest/manifest.go
@@ -565,7 +565,7 @@ func (m *Manifest) Run(app string, cache bool) []error {
 
        for i, name := range m.runOrder() {
                go (*m)[name].runAsync(m, m.prefixForEntry(name, i), app, name, cache, ch)
-               time.Sleep(100 * time.Millisecond)
+               // time.Sleep(100 * time.Millisecond)
        }
```

**Comment by nzoschke** [comment]
It seems to be working very well now with improved synchronization around container starts. Nice work @bobzoller and @ddollar

**Pull request merged**
