### PR TITLE
NAT Gateway

### PR DESCRIPTION
**Pull request by nzoschke**
* Custom handler for EC2 NAT Gateway

Tested working by adding this to kernel.json:

```json
"EIP": {
  "Type": "AWS::EC2::EIP",
  "Properties": {
    "Domain": "vpc"
  }
},
"NatGateway": {
  "Type": "Custom::EC2NatGateway",
  "Properties": {
    "ServiceToken": { "Fn::GetAtt": [ "CustomTopic", "Arn" ] },
    "AllocationId": { "Fn::GetAtt": [ "EIP", "AllocationId" ] },
    "SubnetId": { "Ref": "Subnet0" }
  }
},
```

TODO:
- [ ] [EIP Association](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-eip-association.html)
- [ ] Integrate with private subnets

screen shot 2016-02-10 at 5 22 31 pm

screen shot 2016-02-10 at 5 26 37 pm

### CODE REVIEW

**Comment by cleblanc87** [comment]
This is great!

Given that there is only AZ level HA provided by the NAT gateway, should there should be one gateway provisioned per AZ? Each private subnet could then route through the gateway within the same AZ.

**Comment by nzoschke** [comment]
Yeah, I think that's how it should work too. I'm going to remove the CF bit, merge the custom handler, then we can attack the proper subnet / nat gateway / elastic IP setup

**Comment by nzoschke** [comment]
@ddollar can I get a code review on this?

**Comment by nzoschke** [comment]
## Release Playbook
- [ ] Pass checks
- [ ] Code review
- [ ] Release branch
- [ ] Pass CI
- [ ] Merge into master
- [ ] Release master → pass CI → auto-publish release
- [ ] Update dev and testing racks

**Comment by ddollar** [comment]
:+1:

**Pull request merged**
