### PR TITLE
/resources API endpoint, templates, etc

### PR DESCRIPTION
**Pull request by soulshake**
**Thorough review needed.**

This PR renames `service` to `resource` wherever relevant.

There are some gray areas where I'm not sure the rename makes sense, in particular in `/provider/aws/resource.go`.

I added some tests, but these changes affect some still-untested code.

### CODE REVIEW

**Comment by soulshake** [comment]
[Add /resources API endpoint](https://trello.com/c/heXxLQol/1291-add-resources-api-endpoint)

**Comment by soulshake** [comment]
I'm particularly concerned about [ResourceCreate](https://github.com/convox/rack/blob/e4cc9fbfb0859dbd4ba8a0619ed3600636c8405c/provider/aws/resource.go#L18) vs [createResource](https://github.com/convox/rack/blob/e4cc9fbfb0859dbd4ba8a0619ed3600636c8405c/provider/aws/resource.go#L358). If this talks to AWS, and they refer to it as a `service`, we should probably do the same in functions that make those calls, for clarity's sake.

**Comment by soulshake** [comment]
[Deprecate `convox services`, replace with `convox resources`](https://trello.com/c/Kg8TJiCY/1102-deprecate-convox-services-replace-with-convox-resources)

**Comment by MiguelMoll** [comment]
ResourceCreate vs createResource should be OK. The underlying aws API is calling Cloudformation to create a stack. Nothing with "services". Maybe `createResourceStack` to differentiate? As `createResourceURL` does.

**Comment by soulshake** [comment]
@MiguelMoll I pushed another commit with a bunch more changes, could you check this too please? @ddollar the more eyes the better on this one.
Please have a look at the stuff around `provider/aws/templates/resource/` in particular, as I'm not at all sure I fully understand how those are used.

**Comment by soulshake** [comment]
@ddollar: I had a hard time resolving the merge conflict related to [these changes](https://github.com/convox/rack/commit/6b4dfac9470b463c1f4c64b9ce23eedc36a279be).

Your commit linked above says it "fixed service tests." With your version I kept getting errors like this:

```
$ make templates && cd provider/ && make mocks && cd -
$ go test github.com/convox/rack/provider/aws -test.run TestServiceWebhookURL
Request does not match next cycle.
CYCLE REQUEST:
Method: "POST",
RequestURI: "/",
Operation: "",
Body: `Action=CreateStack&Capabilities.member.1=CAPABILITY_IAM&Parameters.member.1.ParameterKey=CustomTopic&Parameters.member.1.ParameterValue=&Parameters.member.2.ParameterKey=NotificationTopic&Parameters.member.2.ParameterValue=&Parameters.member.3.ParameterKey=Url&Parameters.member.3.ParameterValue=http%3A%2F%2Fnotifications.example.org%2Fsns%3Fendpoint%3Dhttps%253A%252F%252Fwww.example.com&StackName=convox-mywebhook&Tags.member.1.Key=Name&Tags.member.1.Value=mywebhook&Tags.member.2.Key=Rack&Tags.member.2.Value=convox&Tags.member.3.Key=Service&Tags.member.3.Value=webhook&Tags.member.4.Key=System&Tags.member.4.Value=convox&Tags.member.5.Key=Type&Tags.member.5.Value=service&TemplateBody=%0A%7B%0A++%22AWSTemplateFormatVersion%22+%3A+%222010-09-09%22%2C%0A++%22Parameters%22%3A+%7B%0A++++%22Url%22%3A+%7B%0A++++++%22Type%22+%3A+%22String%22%2C%0A++++++%22Description%22+%3A+%22Webhook+URL%2C+e.g.+%27https%3A%2F%2Fgrid.convox.com%2Frack-hook%2F1234%27%22%0A++++%7D%2C%0A++++%22CustomTopic%22%3A+%7B%0A++++++%22Type%22+%3A+%22String%22%2C%0A++++++%22Description%22+%3A+%22%22%0A++++%7D%2C%0A++++%22NotificationTopic%22%3A+%7B%0A++++++%22Type%22+%3A+%22String%22%2C%0A++++++%22Description%22+%3A+%22%22%0A++++%7D%0A++%7D%2C%0A++%22Resources%22%3A+%7B%0A++++%22Notifications%22%3A+%7B%0A++++++%22Type%22+%3A+%22Custom%3A%3ASNSSubscription%22%2C%0A++++++%22Version%22%3A+%221.0%22%2C%0A++++++%22Properties%22%3A+%7B%0A++++++++%22ServiceToken%22%3A+%7B+%22Ref%22%3A+%22CustomTopic%22+%7D%2C%0A++++++++%22TopicArn%22+%3A+%7B+%22Ref%22%3A+%22NotificationTopic%22+%7D%2C%0A++++++++%22Protocol%22+%3A+%22http%22%2C%0A++++++++%22Endpoint%22+%3A+%7B+%22Ref%22%3A+%22Url%22+%7D%0A++++++%7D%0A++++%7D%0A++%7D%2C%0A++%22Outputs%22%3A+%7B%0A++++%22Url%22%3A+%7B%0A++++++%22Value%22%3A+%7B+%22Ref%22%3A+%22Url%22+%7D%0A++++%7D%0A++%7D%0A%7D%0A&Version=2010-05-15`,
ACTUAL REQUEST:
Method: "POST",
RequestURI: "/",
Operation: "",
Body: `Action=DescribeStacks&StackName=mywebhook&Version=2010-05-15`,
-------------->
2017/01/10 16:44:04 SerializationError: failed to decode query XML error response
caused by: EOF
FAIL	github.com/convox/rack/provider/aws	0.007s
```

I ended up going with my version to get the tests to pass. Therefore this PR may overwrite some of your changes in the commit linked above. I don't really understand the changes you made there--I can reintegrate them if needed but would appreciate any guidance you can offer regarding the error above.

**Comment by ddollar** [comment]
Your resource.go -> service.go rename is missing this change from that same PR:

https://github.com/convox/rack/pull/1532/commits/e71d5140523e5a981136c133e68b630dc60be8ab

**Pull request closed without merging**
