### PR TITLE
[WIP] Fix for breaking `convox builds import` when piped in

### PR DESCRIPTION
**Pull request by SonOfBytes**
When using a pipe into `convox builds import` the progress indicator breaks the PostMultiPart file upload resulting in a premature EOF on the server side.

Removing the progress indicator for pipe imports addresses this issue.

See Issue https://github.com/convox/rack/issues/1902 and https://github.com/convox/rack/issues/1609

### CODE REVIEW

**Comment by SonOfBytes** [comment]
I could add another test to build_test that imports a file from fixtures to test the file/-f part of the code.  Thoughts?

**Comment by MiguelMoll** [comment]
[Build import/export flakiness](https://trello.com/c/T5v6zHd0/1843-build-import-export-flakiness)

**Comment by MiguelMoll** [comment]
When testing this change, I noticed 
```
> convox builds import < export.tgz
Importing build... Release: RDGJVQIQXNB
```

Didn't show progress anymore. This PR pointed me in the right direction and found out the real cause and addressed it here. https://github.com/convox/rack/pull/2088

Looking to go in this direction unless anyone thinks otherwise.

**Comment by SonOfBytes** [comment]
ugh didn't tests < version, only | and missed the nuance of `cat foo | convox import` vs `convox import < foo`

sorry :P

Nice catch :D

**Comment by MiguelMoll** [comment]
No worries at all. I'm surprised by the subtle differences. Easy to miss.

**Comment by MiguelMoll** [comment]
Client fix via https://github.com/convox/rack/pull/2088. Thanks again for point us in the right direction. 👍

**Pull request closed without merging**
