### PR TITLE
Update cli pkg and fix panic in container env

### LINKED ISSUE #1368: Cannot link service that is linked to another service
In my project I have 3 services, an api, client and database. The client is linked to the API and the API is linked to database. This linking causes both `convox doctor` and `convox start` to crash with no error. Here is my `docker-compose.yml`

```yml
version: "2"
services:
  client:
    build: ./client
    command: ["node", "."]
    ports:
      - 8080:8080
    environment:
      - API_URL
    links:
      - api
  api:
    build: ./api
    command: ["node", "."]
    ports:
      - 3000:3000
    environment:
      - DB_URL
    links:
      - db
  db:
    image: convox/mongo
    ports:
      - 27017
```

[I made a repository to demonstrate this issue.](https://github.com/lukevella/convox-links-issue)

### LINKED ISSUE #1403: convox start -f fails with status code 1
Getting status code 1 without any message when running `convox start -f docker-compose/development.yml`. However, there is no problem with `convox start -f development.yml`.

### PR DESCRIPTION
**Pull request by awsmsrc**
fixes #1368 
fixes #1403

However, now getting double error output as follows: 

```
⏚ [luke:~/go/src/github.com/lukevella/convox-links-issue] master 12s 1 ± convox start -f foo.yml
ERROR: open foo.yml: no such file or directory
open foo.yml: no such file or directory
```

### CODE REVIEW

**Comment by awsmsrc** [comment]
This is now very close to being good to go, the only remaining issues is that the cli package no longer gracefully handles custom errors: https://github.com/urfave/cli/issues/594, this has broken the special behavior around private console installations and expiring tokens (e.g. prompting for an email and password)

**Comment by MiguelMoll** [comment]
[CLI exits on panic](https://trello.com/c/ddF4kLKc/1684-cli-exits-on-panic)

**Comment by MiguelMoll** [comment]
This change was causing CI to fail in us-west-2

```
++ ci/region.sh 3
+ export AWS_DEFAULT_REGION=us-west-2 AWS_REGION=us-west-2 RACK_PRIVATE=yes
+ AWS_DEFAULT_REGION=us-west-2
+ AWS_REGION=us-west-2
+ RACK_PRIVATE=yes
+ convox install --no-autoscale
+ tee /tmp/circle-artifacts.Va4QPuN/convox-installer.log

ci/install.sh returned exit code 1
```

**Comment by awsmsrc** [comment]
@MiguelMoll can't review as i opened the original pr

But I approve of the stdcli error type

**Comment by MiguelMoll** [comment]
Thats all I needed. 👍 

Going to rebase and should be good to go.

**Pull request closed without merging**
