### PR TITLE
Restrict custom topic role

### PR DESCRIPTION
**Pull request by MiguelMoll**
Taking #2052 forward with changes. Changed a few nitpicks. Also added some more app and rack permissions that require an `*` resource. @ravenac95 Any feedback is welcomed.

### CODE REVIEW

**Comment by MiguelMoll** [comment]
[Restricted Permissions for Custom Topic Role](https://trello.com/c/pg9hsdLH/2146-restricted-permissions-for-custom-topic-role)

**Comment by ravenac95** [comment]
@MiguelMoll changes don't seem bad but I'm curious, are some of the wildcard requirements not capable of being restricted to a specific account? I'm not that adamant about it but I would definitely prefer something more restrictive that more permissive.

**Comment by MiguelMoll** [comment]
That sounds reasonable. I can try messing around with the `Condition` element. AWS docs and my testing pretty much left little else with `Resource`.

**Comment by ravenac95** [comment]
Ahh ok. Ya I think as it stands the IAM role is worlds better than what it was previously.

**Comment by nzoschke** [comment]
This looks really good in general, but we need more time to carefully review the reduced IAM to make sure there will be no regressions.

**Comment by MiguelMoll** [comment]
Better approach would be to handle this with Praxis and it's custom role. Editing the IAM at this point could break existing features.

**Pull request closed without merging**
