### PR TITLE
support exec form for command in docker-compose.yml

### LINKED ISSUE #430: command in docker-compose.yml using *shell form* and not *exec form*
Specifying a `command` in docker-compose appears to always use the *shell form* and not the *exec form*. App runs as subcommand of `/bin/sh -c` (and does not handle signals correctly etc.) and there does not appear to be a way to prevent this.

My understanding is docker-compose.yml should use *exec form* by default.

### `command` in docker-compose.yml overriding default `CMD` in Dockerfile

Dockerfile -
```
FROM node:0.10

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ENV PATH="$PATH:/usr/src/node_modules/.bin"
COPY package.json /usr/src/
RUN cd /usr/src && npm install

COPY . /usr/src/app

CMD [ "npm", "start" ]
```

docker-compose.yml -
```
web:
  build: .
  command: npm start
  ports:
    - 3000:3000
  volumes:
    - .:/usr/src/app
```

Result (subcommand of `sh -c`) -
```
$ convox ps --app express
ID            NAME  RELEASE      SIZE  STARTED        COMMAND
ede8247f8f91  web   RKHIFBJEUAM  256   7 seconds ago  sh -c 'npm start'
```

npm is not pid 1 -
```
root@ede8247f8f91:/usr/src/app# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   4336   720 ?        Ss   13:05   0:00 sh -c npm start
root         6  0.1  0.8 834780 35496 ?        Sl   13:05   0:00 npm
```

### No `command` in docker-compose.yml, default `CMD` in exec form in Dockerfile

Dockerfile -
```
FROM node:0.10

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ENV PATH="$PATH:/usr/src/node_modules/.bin"
COPY package.json /usr/src/
RUN cd /usr/src && npm install

COPY . /usr/src/app

CMD [ "npm", "start" ]
```

docker-compose.yml -
```
web:
  build: .
  #command: npm start
  ports:
    - 3000:3000
  volumes:
    - .:/usr/src/app
```

Result (no subcommand) -
```
$ convox ps --app express
ID            NAME  RELEASE      SIZE  STARTED       COMMAND
54c9e709fa1b  web   RTNYIAOJNZD  256   1 minute ago  npm start
```

npm is pid 1 -
```
root@54c9e709fa1b:/usr/src/app# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  1.3  0.8 834772 35652 ?        Ssl  13:13   0:00 npm
```

From testing it looks like this behavior exists with `entrypoint` also.

### PR DESCRIPTION
**Pull request by soulware**
Add ability to specify `command` in `docker-compose.yml` in exec form - 

```
command: [bundle, exec, thin, -p, 3000]
```
See here for example - https://docs.docker.com/compose/compose-file/#command

Also default to not specifying *any* command if unspecified rather than use `""`.

See here for reasoning - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html

```
Command
The CMD value to pass to the container. For more information about the Docker CMD parameter, see https://docs.docker.com/reference/builder/#cmd.

Required: No

Type: List of strings
```

Fixes #430 

## Release Playbook
- [ ] Rebase against master
- [ ] Pass checks
- [ ] Release branch ()
- [ ] Pass CI ()
- [ ] Code review
- [ ] Merge into master
- [ ] Release master ()
- [ ] Pass CI ()
- [ ] Update dev and testing racks
- [ ] Publish release
- [ ] Release CLI

### CODE REVIEW

**Comment by nzoschke** [comment]
Thanks for this. Looks like a great pass at it. I suspect we'll also need to change the `cmd/formation` handler for the possible new `Custom::ECSTaskDefinition` input

**Comment by soulware** [comment]
Hey @nzoschke - thanks for taking a look. I'm not sure I follow what you mean - I'm not sure how/where docker-compose and `Custom::ECSTaskDefinition` relate to each other?

**Comment by nzoschke** [comment]
Took another look and this looks great and is hopefully very close.

Because the resource in CloudFormation is a Custom::ECSTaskDefinition, convox has a bit more code that creates the actual TaskDefinition. On first look, I think this won't like the new array input, nor will it create the task definition without the 'sh -c':

https://github.com/convox/rack/blob/master/api/cmd/formation/handler/ecs.go

This is a pretty tricky part of the code base. I'd be happy to show you the ropes, or we can discuss a handoff.

**Comment by soulware** [comment]
Taking a look now - seems like the `command` stuff is only a few lines in there. I see what you mean though as it assumes it's a string getting passed in.

**Comment by soulware** [comment]
@nzoschke can you take another look? Compiles but untested...
I'd be interested in knowing how to test this - I'm assuming there is a way of getting convox installed on a rack from a local version?

**Comment by mwarkentin** [comment]
@soulware Not sure if you saw the new development guide? https://github.com/convox/rack/blob/master/Development.md

**Comment by nzoschke** [comment]
@soulware awesome.

I just copied this to https://github.com/convox/rack/tree/command-exec-form and used some internal tools to cut a release from it. You can update your rack with:

```
$ convox rack update 20160330143438-command-exec-form
```

Or install a new one with

```
$ convox install --version 20160330143438-command-exec-form
```

Integration tests are also running against your changes here: https://circleci.com/gh/convox/rack/680

Changes in this layer aren't the easiest to test yet. Some relevant documentation and tooling is:

https://github.com/convox/rack/blob/master/Development.md#infrastructure-changes
https://github.com/convox/rack/blob/master/Development.md#release-changes-for-convox-rack-update
https://github.com/convox/release


What you can do is build a Lambda compatible .zip file for the custom handler:

```
$ cd convox/rack
$ cd api/cmd/formation
$ make formation
```

Then upload this to an existing Rack or App Lambda function.

I believe if you upload it to an existing app then try a deploy that changes the task definition you'll hit your changes. If it isn't working, you'll see some errors in CloudFormation for the task definition or CloudWatch Logs for the lambda function.

This can be pretty tough to debug so thanks for working on it and providing feedback.

**Comment by soulware** [comment]
@nzoschke ok ecs.go should be handling Command coming in as one of `string` or `[]interface{}` now.
Let me know if you build a new version and I can upgrade my test rack and test it out.

**Comment by soulware** [comment]
From testing this out against a test rack - 

exec form in docker-compose.yml - `command: [/usr/local/bin/node, index.js]` -
```
$ convox ps --app express
ID            NAME  RELEASE      SIZE  STARTED        COMMAND                     
7ac1fd7a0492  web   RQKFEWUIDES  256   4 minutes ago  /usr/local/bin/node index.js
f22ce23a23cf  web   RQKFEWUIDES  256   4 minutes ago  /usr/local/bin/node index.js
```

shell form in docker-compose.yml - `command: /usr/local/bin/node, index.js` -
```
$ convox ps --app express
ID            NAME  RELEASE      SIZE  STARTED         COMMAND                             
7ce8c60042da  web   REXXFIUTHFM  256   40 seconds ago  sh -c '/usr/local/bin/node index.js'
8c7d7f111d78  web   REXXFIUTHFM  256   41 seconds ago  sh -c '/usr/local/bin/node index.js'
```

**Comment by nzoschke** [comment]
Thanks! I'm closing this and opening https://github.com/convox/rack/pull/508 to test/merge/release this patch.

**Pull request closed without merging**
