### PR TITLE
[RELEASE] 20170125-2

### PR DESCRIPTION
**Pull request by MiguelMoll**
## Pull Requests
  - closes #1548 Paginate task listings [@ddollar]
  - closes #1604 Validate required `registries add` args [@ianmalott]
  - closes #1615 New strategy for Rack service replacement [@ddollar]
  - closes #1616 readonly ecr permissions [@MiguelMoll]
  - closes #1621 option to disable autoscale during install [@MiguelMoll]

## Milestone Release
- [x] Release branch
- [x] Pass CI
- [x] Code review
- [ ] Merge into master
- [ ] Close milestone
- [ ] Release master
- [ ] Record release number: 
- [ ] Pass CI
- [ ] Update demo
- [ ] Deploy demo/httpd
- [ ] Deploy demo/rails
- [ ] Update staging
- [ ] Deploy staging/site-staging
- [ ] Deploy staging/console-staging
- [ ] Update [release notes](https://github.com/convox/rack/releases)
- [ ] Documentation review
- [ ] Publish release
- [ ] Release CLI

### CODE REVIEW

**Comment by MiguelMoll** [comment]
[20170125-2](https://trello.com/c/t6plRJHT/1705-20170125-2)

**Comment by mattmanning** [comment]
[Can't add rack's own registry as a private registry](https://trello.com/c/7NjdQKDT/1710-can-t-add-rack-s-own-registry-as-a-private-registry)

**Comment by mattmanning** [comment]
[--no-autoscale installer option](https://trello.com/c/AlK8eXBy/1712-no-autoscale-installer-option)

**Comment by mattmanning** [comment]
Docs review is done. See linked trello cards above

**Comment by soulshake** [comment]
[Add an Autoscale checkbox to the web installer](https://trello.com/c/A3Pz8tIK/1884-add-an-autoscale-checkbox-to-the-web-installer)

**Pull request merged**
