### PR TITLE
Apply privileged from manifest

### PR DESCRIPTION
**Pull request by mattmanning**
This enhances `convox start`.

I want to use s3fs. In order to access `/dev/fuse` I need to pass the `--privileged` flag to `docker run`. This reads it from `docker-compose.yml` into the Manifest struct and then sets it on the command if true.

https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

### CODE REVIEW

**Comment by nzoschke** [comment]
This looks good for `convox start`. We also want to set this flag in the ECS task definition. See this issue for more info:

https://github.com/convox/rack/issues/155

**Comment by nzoschke** [comment]
Are we doing the right thing in CF template and handler with the boolean? Should it be "true" and "false" or true and false?

**Comment by mattmanning** [comment]
This works great for me, but now I get a message like:

    ERROR: read tcp 172.17.0.5:57035->10.0.2.25:2376: io: read/write on closed pipe

Every time I run a `convox exec` command. So far I haven't been able to figure out exactly where that's coming from.

**Comment by mattmanning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;gVfqSVAt&#x2F;328-apply-privileged-from-manifest"> Apply privileged from manifest</a>

**Comment by nzoschke** [comment]
I just verified that this error is not unique to this branch. Merging and will track down the closed pipe error later.

**Pull request merged**
