### PR TITLE
[RELEASE] 20170605

### PR DESCRIPTION
**Pull request by nzoschke**
## Pull Requests
  - closes #2214 Listener Parameter combines Host and Certificate parameters [@nzoschke]
  - closes #2216 Clean up old build images [@nzoschke]

## Milestone Release
- [x] Release branch (20170605183502-20170605)
- [x] Pass CI
- [x] Code review
- [x] Merge into master
- [ ] Close milestone
- [ ] Release master
- [ ] Record release number: 
- [ ] Pass CI
- [ ] Update demo
- [ ] Deploy demo/httpd
- [ ] Deploy demo/rails
- [ ] Update staging
- [ ] Deploy staging/site-staging
- [ ] Deploy staging/console-staging
- [ ] Verbose [release notes](https://github.com/convox/rack/releases)
- [ ] Documentation review
- [ ] Publish release
- [ ] Release CLI

### CODE REVIEW

**Comment by ddollar** [comment]
[20170605](https://trello.com/c/TFr1ooU3/2517-20170605)

**Comment by nzoschke** [comment]
Deploy demo/httpd

Before

```
$ convox apps params
NAME                  VALUE
Cluster               convox-demo-Cluster-ULPOC094DVN9
DeploymentMaximum     200
DeploymentMinimum     50
Environment           https://convox-demo-httpd-settings-32q4xd2uvu8l.s3.amazonaws.com/releases/RXRFXFSYZBR/env
Internal              No
Key                   arn:aws:kms:us-west-2:849058742300:key/cfc63985-61df-4760-b3cd-7aa3b1cfc3f1
NativeLogging         No
Private               No
Release               RXRFXFSYZBR
Repository
SecurityGroup
Subnets               subnet-03a27e64,subnet-39712861,subnet-eebe48a7
SubnetsPrivate        subnet-03a27e64,subnet-39712861,subnet-eebe48a7
TaskRole
VPC                   vpc-8945fbee
VPCCIDR               10.0.0.0/16
Version               20170531220422
WebFormation          2,10,50
WebPort80Certificate
WebPort80Host         17986
```

After

```
$ convox apps params
NAME               VALUE
Cluster            convox-demo-Cluster-ULPOC094DVN9
DeploymentMaximum  200
DeploymentMinimum  50
Environment        https://convox-demo-httpd-settings-32q4xd2uvu8l.s3.amazonaws.com/releases/RZUAQEPQXSS/env
Internal           No
Key                arn:aws:kms:us-west-2:849058742300:key/cfc63985-61df-4760-b3cd-7aa3b1cfc3f1
NativeLogging      No
Private            No
Release            RZUAQEPQXSS
Repository
SecurityGroup
Subnets            subnet-03a27e64,subnet-39712861,subnet-eebe48a7
SubnetsPrivate     subnet-03a27e64,subnet-39712861,subnet-eebe48a7
TaskRole
VPC                vpc-8945fbee
VPCCIDR            10.0.0.0/16
Version            20170606013346
WebFormation       2,10,50
WebPort80Listener  17986,
$ convox apps params
NAME               VALUE
Cluster            convox-demo-Cluster-ULPOC094DVN9
DeploymentMaximum  200
DeploymentMinimum  50
Environment        https://convox-demo-httpd-settings-32q4xd2uvu8l.s3.amazonaws.com/releases/RZUAQEPQXSS/env
Internal           No
Key                arn:aws:kms:us-west-2:849058742300:key/cfc63985-61df-4760-b3cd-7aa3b1cfc3f1
NativeLogging      No
Private            No
Release            RZUAQEPQXSS
Repository
SecurityGroup
Subnets            subnet-03a27e64,subnet-39712861,subnet-eebe48a7
SubnetsPrivate     subnet-03a27e64,subnet-39712861,subnet-eebe48a7
TaskRole
VPC                vpc-8945fbee
VPCCIDR            10.0.0.0/16
Version            20170606013346
WebFormation       2,10,50
WebPort80Listener  17986,
```

**Comment by nzoschke** [comment]
Deploy demo/rails

Before

```
$ convox apps params
NAME                         VALUE
Cluster                      convox-demo-Cluster-ULPOC094DVN9
DatabaseFormation            1,0,256
DatabasePort5432Certificate
DatabasePort5432Host         11336
DeploymentMaximum            200
DeploymentMinimum            50
Environment                  https://convox-demo-rails-settings-gst5o8p8bshi.s3.amazonaws.com/releases/RSYLBFWJTQE/env
Internal                     No
Key                          arn:aws:kms:us-west-2:849058742300:key/cfc63985-61df-4760-b3cd-7aa3b1cfc3f1
NativeLogging                No
Private                      No
Release                      RSYLBFWJTQE
Repository
SecurityGroup
Subnets                      subnet-03a27e64,subnet-39712861,subnet-eebe48a7
SubnetsPrivate               subnet-03a27e64,subnet-39712861,subnet-eebe48a7
TaskRole
VPC                          vpc-8945fbee
VPCCIDR                      10.0.0.0/16
Version                      20170531220422
WebFormation                 1,10,512
WebPort443Certificate        arn:aws:iam::849058742300:server-certificate/cert-convox-demo-1484592839-25263
WebPort443Host               21956
WebPort80Certificate
WebPort80Host                51933
```

After

```
$ convox apps params
NAME                      VALUE
Cluster                   convox-demo-Cluster-ULPOC094DVN9
DatabaseFormation         1,0,256
DatabasePort5432Listener  11336,
DeploymentMaximum         200
DeploymentMinimum         50
Environment               https://convox-demo-rails-settings-gst5o8p8bshi.s3.amazonaws.com/releases/RSDDSDYYYEO/env
Internal                  No
Key                       arn:aws:kms:us-west-2:849058742300:key/cfc63985-61df-4760-b3cd-7aa3b1cfc3f1
NativeLogging             No
Private                   No
Release                   RSDDSDYYYEO
Repository
SecurityGroup
Subnets                   subnet-03a27e64,subnet-39712861,subnet-eebe48a7
SubnetsPrivate            subnet-03a27e64,subnet-39712861,subnet-eebe48a7
TaskRole
VPC                       vpc-8945fbee
VPCCIDR                   10.0.0.0/16
Version                   20170606013346
WebFormation              1,10,512
WebPort443Listener        21956,arn:aws:iam::849058742300:server-certificate/cert-convox-demo-1484592839-25263
WebPort80Listener         51933,
```

**Comment by nzoschke** [comment]
Deploy staging/site-staging

Before

```
$ convox apps params --app site-staging
NAME                   VALUE
Cluster                convox-staging-Cluster-IYETTGCVUDH5
DeploymentMaximum      200
DeploymentMinimum      50
Environment            ***
Internal               No
Key                    arn:aws:kms:us-east-1:782231114432:key/4003732a-664c-403a-ac6e-e688d1092e55
NativeLogging          No
Private                No
Release                RIWIQNKLFDM
Repository
SecurityGroup
Subnets                subnet-c61966eb,subnet-9fcde0d6,subnet-4bf14b77
SubnetsPrivate         subnet-c61966eb,subnet-9fcde0d6,subnet-4bf14b77
TaskRole
VPC                    vpc-35bb0153
VPCCIDR                10.0.0.0/16
Version                20170531220422
WebFormation           2,0,256
WebPort443Certificate  arn:aws:acm:us-east-1:782231114432:certificate/4dc092d9-f570-4d7f-9873-d1cf956c7dba
WebPort443Host         7143
WebPort80Certificate
WebPort80Host          53954
```

After

```
$ convox apps params --app site-staging
NAME                VALUE
Cluster             convox-staging-Cluster-IYETTGCVUDH5
DeploymentMaximum   200
DeploymentMinimum   50
Environment         ***
Internal            No
Key                 arn:aws:kms:us-east-1:782231114432:key/4003732a-664c-403a-ac6e-e688d1092e55
NativeLogging       No
Private             No
Release             RYVFQUOIWIP
Repository
SecurityGroup
Subnets             subnet-c61966eb,subnet-9fcde0d6,subnet-4bf14b77
SubnetsPrivate      subnet-c61966eb,subnet-9fcde0d6,subnet-4bf14b77
TaskRole
VPC                 vpc-35bb0153
VPCCIDR             10.0.0.0/16
Version             20170606013346
WebFormation        2,0,256
WebPort443Listener  7143,arn:aws:acm:us-east-1:782231114432:certificate/4dc092d9-f570-4d7f-9873-d1cf956c7dba
WebPort80Listener   53954,
```

**Pull request merged**
