### PR TITLE
amzn-ami-2015.09.g-amazon-ecs-optimized

### PR DESCRIPTION
**Pull request by nzoschke**
I want to release this with https://github.com/convox/rack/pull/509

### CODE REVIEW

**Comment by mwarkentin** [comment]
@nzoschke Kind of like washing your car makes it rain,.

> Dear Amazon ECS customer:

> We recently released a new Amazon ECS-optimized AMI that includes Amazon Linux 2016.03 and addresses an issue that causes the agent to stop accepting incoming requests. You can see all of the recent updates in our agent release notes. [1] 

> We recommend that you update to the latest Amazon ECS-optimized AMI. You can find the latest Amazon ECS-optimized AMI version and the process to launch container instances in the documentation. [2] 

> If you are using an Auto Scaling group for the EC2 instances in your cluster, you should create a new launch configuration with the latest Amazon ECS-optimized AMI. [3] 

> Sincerely, 
The Amazon ECS Team

> [1] https://github.com/aws/amazon-ecs-agent/releases
[2] http://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html
[3] http://docs.aws.amazon.com/AutoScaling/latest/DeveloperGuide/WorkingWithLaunchConfig.html

**Comment by mwarkentin** [comment]
```
Region	AMI Name	AMI ID
us-east-1	amzn-ami-2016.03.a-amazon-ecs-optimized	ami-67a3a90d
us-west-1	amzn-ami-2016.03.a-amazon-ecs-optimized	ami-b7d5a8d7
us-west-2	amzn-ami-2016.03.a-amazon-ecs-optimized	ami-c7a451a7
eu-west-1	amzn-ami-2016.03.a-amazon-ecs-optimized	ami-9c9819ef
eu-central-1	amzn-ami-2016.03.a-amazon-ecs-optimized	ami-9aeb0af5
ap-northeast-1	amzn-ami-2016.03.a-amazon-ecs-optimized	ami-7e4a5b10
ap-southeast-1	amzn-ami-2016.03.a-amazon-ecs-optimized	ami-be63a9dd
ap-southeast-2	amzn-ami-2016.03.a-amazon-ecs-optimized	ami-b8cbe8db
```

**Comment by nzoschke** [comment]
Re-opening to pull in the freshest images...

**Comment by nzoschke** [comment]
See https://github.com/convox/rack/pull/517 for latest AMIs

**Pull request merged**
