### PR TITLE
Prevent unbound apps from being promoted

### PR DESCRIPTION
**Pull request by MiguelMoll**
Logic here checks if an app is not bound (that is, it doesn't have a "Name" tag), it's not allowed to be promoted.

### CODE REVIEW

**Comment by MiguelMoll** [comment]
Question: Do we want to deprecate this feature first before outright preventing it?

**Comment by MiguelMoll** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;SNE3RtUJ&#x2F;318-manifest-refactor"> manifest refactor</a>

**Comment by MiguelMoll** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;TthXVAkV&#x2F;397-block-promotion-of-unbound-apps"> block promotion of &quot;unbound&quot; apps</a>

**Comment by MiguelMoll** [comment]
Merging directly into `one_manifest_rebase`

**Comment by matthewford** [comment]
@MiguelMoll running into `ERROR: unbound apps are no longer supported for promotion`, my compose file has a web process and a worker (unbound).

**Comment by MiguelMoll** [comment]
Hey @matthewford, is the app you're trying to promote inf act an "unbound" app? We have a guide [here](https://convox.com/docs/updating-old-apps/) on how to upgrade to the a "bound" apps as unbound apps are no longer supported.

**Pull request closed without merging**
