### PR TITLE
Init v2

### LINKED ISSUE #1121: convox init setups a compose v1 file
I could not find the repository for convox CLI to submit a PR... but wouldn't it be better if `convox init` setup a v2 docker-compose.yml directly?

Not sure if this command gets used a lot, but I just did, and thought that it would be neat if it automatically setup the current version. Or at least a `convox init --version=2`?

### PR DESCRIPTION
**Pull request by awsmsrc**
fixes #1121 

also fixes an issue where manifest yaml output had an empty networks hash

### CODE REVIEW

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;LGuqrkBW&#x2F;557-init-v2"> init v2</a>

**Comment by ddollar** [comment]
Seems like unrelated IAM changes in this PR

**Comment by awsmsrc** [comment]
AMI changes removed

**Comment by ddollar** [comment]
Is it possible to add some simple tests to this?

**Pull request closed without merging**
