### PR TITLE
use ecr for image hosting

### PR DESCRIPTION
**Pull request by ddollar**
The next time an application is pushed an ECR repository will be created and images will be hosted and run from there instead.

Two new app outputs:
* `RegistryId`
* `RegistryRepository`

### CODE REVIEW

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;aK2ZJTHZ&#x2F;294-ecr"> ecr</a>

**Comment by nzoschke** [comment]
Do you need two deploys to switch over to ECR? First one will build + push to existing registry, then deploy will provision a new ECR. Next one will use new ECR.

**Comment by nzoschke** [comment]
:+1:!

Really eager to get this merged and into testing...

**Comment by ddollar** [comment]
Yes, one deploy to turn it on. Next deploy (and all future) go to ECR.

**Comment by nzoschke** [comment]
- [ ] rebase
- [ ] branch release
- [ ] test rack updates
- [ ] test app deploys
- [ ] merge
- [ ] release

**Comment by nzoschke** [comment]
Notes for documentation...

Per app repository. 

Requires two deploys... First one pushes to existing registry and prepares new repository (RUNNING: docker push convox-826133048.us-east-1.elb.amazonaws.com:5000/httpd-web:BCXGMCPAGQN). 

Second one pushes to new repository (RUNNING: docker push 132866487567.dkr.ecr.us-east-1.amazonaws.com/httpd-kcietgppbz:web.BESNIHHSAFW).

"0 images are currently stored in this repository. Amazon ECR limits the number of images to 500 per repository. To request a limit increase click here."

**Pull request merged**
