### PR TITLE
track success/error/warning events around BuildCreate and BuildExecute

### PR DESCRIPTION
**Pull request by nzoschke**

### CODE REVIEW

**Comment by awsmsrc** [comment]
my only comment here is the track code is in two places,
perhaps the trackerror/server functions should also be in helpers and take an error?

That way the error remains a representation of data and helpers remains a package that "does" something.

I totally get that this comment is nitpicky.... not important enough to argue about

**Comment by awsmsrc** [comment]
love anything we can measure :)

**Comment by nzoschke** [comment]
yeah I ponderd this... I was close to putting the success helper in httperr but that didn't seem right.

**Comment by nzoschke** [comment]
I like moving it all to helpers. I'll tack that on now.

**Comment by awsmsrc** [comment]
yeah so the choices are ignore my comment or put all the tracking in helpers and pass the error in to there and do all tracking in the helpers

**Comment by awsmsrc** [comment]
the functionality has my :+1: though

**Comment by nzoschke** [comment]
ok changed my mind, going to ignore your comment for now. helpers and httperr do need to be reconciled since both have segment and rollbar stuff.

But I'll let this bake a bit first and make sure its working and useful, then keep adding more measuring and refactoring the utilities.

**Comment by nzoschke** [comment]
My own review caught something... need to report a final build success deeper in the build model.

**Comment by nzoschke** [comment]
This is another factoring smell:

```
 	NotifySuccess("build:create", map[string]string{"id": b.Id, "app": b.App})
  	fmt.Printf("ns=kernel cn=build at=ExecuteRemote state=success step=build.execute app=%q build=%q\n", b.App, b.Id)
 	helpers.TrackSuccess("Build", "ExecuteRemote")
```

tracking / notifying / logging seems ripe for unification

**Comment by awsmsrc** [comment]
:+1:

**Comment by nzoschke** [comment]
Going to try a new release playbook where we don't do a release branch.

## Release Playbook
- [ ] Rebase against master
- [ ] Pass checks
- [ ] Code review
- [ ] Merge into master
- [ ] Release master
- [ ] Pass CI
- [ ] Update dev and testing racks
- [ ] If rack or app formation changes, test upgrade → re-deploy existing app → downgrade cycle
- [ ] Publish release
- [ ] Release CLI

**Pull request merged**
