### PR TITLE
amzn-ami-2016.03.a-amazon-ecs-optimized

### PR DESCRIPTION
**Pull request by nzoschke**
Followup to https://github.com/convox/rack/pull/512, releasing with https://github.com/convox/rack/pull/509

### CODE REVIEW

**Comment by nzoschke** [comment]
These are failing CI everywhere. Investigating.

**Comment by mwarkentin** [comment]
Looks like the branch and master builds both passed - might've just been a travis glitch?

**Comment by nzoschke** [comment]
I'm seeing failures on the CircleCI tests that install convox and deploy some apps. https://circleci.com/gh/convox/rack/697

Docker and the ecs-agent are no longer starting correctly, so the installer hang on 'waiting for load balancer' because the Rack API containers never start.

In the System logs I see:

```
Starting docker:  .[  OK  ]
...
Stopping docker: [  OK  ]

Starting docker:  [   74.881933] device-mapper: thin: Deletion of thin device 1 failed.
..........[FAILED]

convox start/running, process 2746
Error: Instances does not specify any metadata
```

In /var/log/docker I see:

```
\nWed Apr  6 16:54:22 UTC 2016\n
time="2016-04-06T16:54:22.564322804Z" level=info msg="API listen on /var/run/docker.sock"
\nWed Apr  6 16:54:46 UTC 2016\n
time="2016-04-06T16:54:46.638616670Z" level=warning msg="/!\\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\\"
time="2016-04-06T16:54:46.640209532Z" level=info msg="API listen on /var/run/docker.sock"
time="2016-04-06T16:54:46.640256085Z" level=info msg="API listen on [::]:2376"
time="2016-04-06T16:54:46.951542366Z" level=fatal msg="Error starting daemon: error initializing graphdriver: Device is Busy"
```

Manually doing an `service docker start && start ecs` on the box long after it has initialized brings an instance back into the cluster.

**Comment by nzoschke** [comment]
This patch to the convox userdata seems to work. Adding a magic sleep constant doesn't feel great.

```diff
diff --git a/api/dist/kernel.json b/api/dist/kernel.json
index 2d4cdd9..720f4a8 100644
--- a/api/dist/kernel.json
+++ b/api/dist/kernel.json
@@ -871,7 +871,7 @@
               { "Fn::Join": [ "", [ "echo 'OPTIONS=\"${OPTIONS} --log-opt max-file=2 --log-opt max-size=50m --insecure-registry=", { "Fn::Join": [ ":", [ { "Fn::GetAtt": [ "Balancer", "DNSName" ] }, "5000" ] ] }, " --host=unix:///var/run/docker.sock --host=0.0.0.0:2376\"' >> /etc/sysconfig/docker" ] ] },
               "echo 'OPTIONS=\"${OPTIONS} --log-opt max-file=2 --log-opt max-size=50m --host=unix:///var/run/docker.sock  --host=0.0.0.0:2376\"' >> /etc/sysconfig/docker"
             ] },
-            "service docker restart",
+            "sleep 60; service docker restart ; start ecs",
             "mkdir -p /etc/convox",
             { "Fn::Join": [ "", [ "echo \"", { "Ref": "AWS::Region" }, "\" > /etc/convox/region" ] ] },
             { "Fn::Join": [ "", [ "echo \"", { "Ref": "Kinesis" }, "\" > /etc/convox/kinesis" ] ] },
```

**Comment by nzoschke** [comment]
I just got this advice...

> I would discourage people from doing "service docker restart" in userdata.  Instead, a #cloud-boothook or a #cloud-config with a bootcmd should be used to configure Docker before the first time it starts.

**Pull request merged**
