### PR TITLE
NativeLogging app parameter to turn on awslogs driver and turn off convox/agent logging

### PR DESCRIPTION
**Pull request by nzoschke**
There are reports of very high volumes of logging causing something in the Docker -> convox/agent -> CloudWatch Logs pipeline to fail.

A manual test of the native `awslogs` ECS -> CloudWatch Logs integration was observed to be more robust.

This patch offers a path to turn on the native `awslogs` driver for any app, which is enabled `convox apps params set NativeLogging=Yes` command.

The `awslogs` driver does not prefix logs with human-friendly information about process name, release, or id. This patch adds that prefix back at `convox logs` read time by introspecting ECS.

The `awslogs` driver does not add any additional information about containers starting or stopping, like `convox/agent` does. This delegates that responsibility to the recent release that adds ECS event logs into an app stream.

This patch does not change the syslog resource, so apps that use both NativeLogging and syslog forwarding will not get human-friendly information in the forwarded logs.

## TODO
- [x] Set LogConfiguration in App Task Definition
- [x] Remove LOG_GROUP from App Task Environment
- [x] Strategy to include release in log line prefix (`web:RRQSKTNDULA/0b4127231289`)
- [x] Strategy to retain agent container management logs `agent:0.70/i-02202a40cf58f7e75 Dead web process 0b4127231289`
- [x] Test syslog
- [ ] Eventually update convox/agent

## QA Checklist
- [ ] Create branch release and update rack to it
- [ ] Deploy an app and see NativeLogging=No parameter
- [ ] Verify task definition LOG_GROUP is set and LogConfiguration is empty
- [ ] Verify `convox logs` show convox/agent style logs
- [ ] `convox app params set NativeLogging=Yes`
- [ ] Verify task definition LOG_GROUP is empty and LogConfiguration is set
- [ ] Verify `convox logs` shows app logs

### CODE REVIEW

**Comment by nzoschke** [comment]
I'm QAing this on top of the https://github.com/convox/rack/pull/2074 which has app CloudFormation and ECS logs. Some observations:

- [ ] `ERROR: InvalidParameter: 1 validation error(s) found. - minimum field size of 1, FilterLogEventsInput.LogGroupName.` error on `convox logs` for a very newly creating app
- [ ] [CFM] vs [CFN] prefix
- [ ] No app convox/agent logs is intentional, but loses ordered log lines about containers starting and stopping
- [ ] ECS logs come after app stdout logs (related to above)
- [ ] App logs missing during an existing `convox logs` session then a scale
- [ ] Inconsistent ordering on a historic `convox logs`

Here's the current log history for a newly created and scaled app:

```
$ convox logs --since=2h
2017-03-20T18:04:25Z [CFM] resource="dev-httpd" status="CREATE_IN_PROGRESS" reason="User Initiated"
2017-03-20T18:04:36Z [CFM] resource="LogGroup" status="CREATE_IN_PROGRESS" reason=""
2017-03-20T18:04:37Z [CFM] resource="Settings" status="CREATE_IN_PROGRESS" reason=""
2017-03-20T18:04:37Z [CFM] resource="LogGroup" status="CREATE_IN_PROGRESS" reason="Resource creation Initiated"
2017-03-20T18:04:37Z [CFM] resource="CustomTopicRole" status="CREATE_IN_PROGRESS" reason="Resource creation Initiated"
2017-03-20T18:04:38Z [CFM] resource="Settings" status="CREATE_IN_PROGRESS" reason="Resource creation Initiated"
2017-03-20T18:04:57Z [CFM] resource="CustomTopicRole" status="CREATE_COMPLETE" reason=""
2017-03-20T18:05:01Z [CFM] resource="Settings" status="CREATE_COMPLETE" reason=""
2017-03-20T18:05:03Z [CFM] resource="CustomTopic" status="CREATE_IN_PROGRESS" reason=""
2017-03-20T18:05:05Z [CFM] resource="CustomTopic" status="CREATE_IN_PROGRESS" reason="Resource creation Initiated"
2017-03-20T18:05:05Z [CFM] resource="CustomTopic" status="CREATE_COMPLETE" reason=""
2017-03-20T18:05:16Z [CFM] resource="RegistryRepository" status="CREATE_IN_PROGRESS" reason="Resource creation Initiated"
2017-03-20T18:05:17Z [CFM] resource="RegistryRepository" status="CREATE_COMPLETE" reason=""
2017-03-20T18:05:24Z [CFM] resource="dev-httpd" status="CREATE_COMPLETE" reason=""
2017-03-20T18:07:02Z [CFM] resource="dev-httpd" status="UPDATE_IN_PROGRESS" reason="User Initiated"
2017-03-20T18:07:19Z [CFM] resource="WebECSTaskDefinition" status="CREATE_IN_PROGRESS" reason="Resource creation Initiated"
2017-03-20T18:07:20Z [CFM] resource="WebECSTaskDefinition" status="CREATE_COMPLETE" reason=""
2017-03-20T18:07:39Z [CFM] resource="BalancerWebSecurityGroup" status="CREATE_IN_PROGRESS" reason="Resource creation Initiated"
2017-03-20T18:07:48Z [CFM] resource="BalancerWeb" status="CREATE_COMPLETE" reason=""
2017-03-20T18:07:54Z [CFM] resource="ServiceWeb" status="CREATE_IN_PROGRESS" reason="Resource creation Initiated"
2017-03-20T18:08:11Z [ECS] event="service dev-httpd-ServiceWeb-1274TTQ2F7LR0 has started 1 tasks: task ef76746b-1fcd-4185-a74f-6a4f5a8037ae."
2017-03-20T18:08:11Z [ECS] service="dev-httpd-ServiceWeb-1274TTQ2F7LR0" task="ef76746b-1fcd-4185-a74f-6a4f5a8037ae" status="PENDING" container="web"
2017-03-20T18:08:12Z [ECS] service="dev-httpd-ServiceWeb-1274TTQ2F7LR0" task="ef76746b-1fcd-4185-a74f-6a4f5a8037ae" status="RUNNING" container="web"
2017-03-20T18:08:12Z [ECS] event="service dev-httpd-ServiceWeb-1274TTQ2F7LR0 has started 1 tasks: task ef76746b-1fcd-4185-a74f-6a4f5a8037ae."
2017-03-20T18:08:12Z [ECS] service="dev-httpd-ServiceWeb-1274TTQ2F7LR0" task="ef76746b-1fcd-4185-a74f-6a4f5a8037ae" status="PENDING" container="web"
2017-03-20T18:09:01Z [CFM] resource="dev-httpd" status="UPDATE_COMPLETE_CLEANUP_IN_PROGRESS" reason=""
2017-03-20T18:17:34Z [CFM] resource="dev-httpd" status="UPDATE_IN_PROGRESS" reason="User Initiated"
2017-03-20T18:17:50Z [CFM] resource="ServiceWeb" status="UPDATE_IN_PROGRESS" reason=""
2017-03-20T18:18:16Z [ECS] event="service dev-httpd-ServiceWeb-1274TTQ2F7LR0 has started 1 tasks: task ef76746b-1fcd-4185-a74f-6a4f5a8037ae."
2017-03-20T18:18:16Z [ECS] service="dev-httpd-ServiceWeb-1274TTQ2F7LR0" task="3fd0ff97-5e4e-4271-a705-d9aace843542" status="PENDING" container="web"
2017-03-20T18:18:16Z [ECS] event="service dev-httpd-ServiceWeb-1274TTQ2F7LR0 registered 1 instances in elb httpd-web-SJ6R77B"
2017-03-20T18:18:16Z [ECS] event="service dev-httpd-ServiceWeb-1274TTQ2F7LR0 has reached a steady state."
2017-03-20T18:18:30Z [ECS] service="dev-httpd-ServiceWeb-1274TTQ2F7LR0" task="3fd0ff97-5e4e-4271-a705-d9aace843542" status="PENDING" container="web"
2017-03-20T18:18:30Z [ECS] event="service dev-httpd-ServiceWeb-1274TTQ2F7LR0 has started 1 tasks: task 3fd0ff97-5e4e-4271-a705-d9aace843542."
2017-03-20T18:18:30Z [ECS] event="service dev-httpd-ServiceWeb-1274TTQ2F7LR0 has reached a steady state."
2017-03-20T18:18:30Z [ECS] event="service dev-httpd-ServiceWeb-1274TTQ2F7LR0 registered 1 instances in elb httpd-web-SJ6R77B"
2017-03-20T18:18:30Z [ECS] event="service dev-httpd-ServiceWeb-1274TTQ2F7LR0 has started 1 tasks: task ef76746b-1fcd-4185-a74f-6a4f5a8037ae."
2017-03-20T18:18:31Z [ECS] service="dev-httpd-ServiceWeb-1274TTQ2F7LR0" task="3fd0ff97-5e4e-4271-a705-d9aace843542" status="RUNNING" container="web"
2017-03-20T18:18:58Z [CFM] resource="dev-httpd" status="UPDATE_COMPLETE" reason=""
2017-03-20T18:04:36Z [CFM] resource="CustomTopicRole" status="CREATE_IN_PROGRESS" reason=""
2017-03-20T18:04:36Z [CFM] resource="ServiceRole" status="CREATE_IN_PROGRESS" reason=""
2017-03-20T18:04:37Z [CFM] resource="ServiceRole" status="CREATE_IN_PROGRESS" reason="Resource creation Initiated"
2017-03-20T18:04:37Z [CFM] resource="LogGroup" status="CREATE_COMPLETE" reason=""
2017-03-20T18:04:57Z [CFM] resource="ServiceRole" status="CREATE_COMPLETE" reason=""
2017-03-20T18:05:10Z [CFM] resource="RegistryRepository" status="CREATE_IN_PROGRESS" reason=""
2017-03-20T18:07:15Z [CFM] resource="WebECSTaskDefinition" status="CREATE_IN_PROGRESS" reason=""
2017-03-20T18:07:22Z [CFM] resource="BalancerWebSecurityGroup" status="CREATE_IN_PROGRESS" reason=""
2017-03-20T18:07:40Z [CFM] resource="BalancerWebSecurityGroup" status="CREATE_COMPLETE" reason=""
2017-03-20T18:07:45Z [CFM] resource="BalancerWeb" status="CREATE_IN_PROGRESS" reason=""
2017-03-20T18:07:47Z [CFM] resource="BalancerWeb" status="CREATE_IN_PROGRESS" reason="Resource creation Initiated"
2017-03-20T18:07:53Z [CFM] resource="ServiceWeb" status="CREATE_IN_PROGRESS" reason=""
2017-03-20T18:08:04Z web:RXNAPZUJWQP/ef76746b1fcd AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.6. Set the 'ServerName' directive globally to suppress this message
2017-03-20T18:08:04Z web:RXNAPZUJWQP/ef76746b1fcd AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.6. Set the 'ServerName' directive globally to suppress this message
2017-03-20T18:08:04Z web:RXNAPZUJWQP/ef76746b1fcd [Mon Mar 20 18:08:04.015433 2017] [mpm_event:notice] [pid 1:tid 140493614700416] AH00489: Apache/2.4.25 (Unix) configured -- resuming normal operations
2017-03-20T18:08:04Z web:RXNAPZUJWQP/ef76746b1fcd [Mon Mar 20 18:08:04.016042 2017] [core:notice] [pid 1:tid 140493614700416] AH00094: Command line: 'httpd -D FOREGROUND'
2017-03-20T18:08:55Z [CFM] resource="ServiceWeb" status="CREATE_COMPLETE" reason=""
2017-03-20T18:09:04Z [CFM] resource="dev-httpd" status="UPDATE_COMPLETE" reason=""
2017-03-20T18:18:29Z web:RXNAPZUJWQP/3fd0ff975e4e AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.5. Set the 'ServerName' directive globally to suppress this message
2017-03-20T18:18:29Z web:RXNAPZUJWQP/3fd0ff975e4e AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.5. Set the 'ServerName' directive globally to suppress this message
2017-03-20T18:18:29Z web:RXNAPZUJWQP/3fd0ff975e4e [Mon Mar 20 18:18:29.473998 2017] [mpm_event:notice] [pid 1:tid 139676073478016] AH00489: Apache/2.4.25 (Unix) configured -- resuming normal operations
2017-03-20T18:18:29Z web:RXNAPZUJWQP/3fd0ff975e4e [Mon Mar 20 18:18:29.474649 2017] [core:notice] [pid 1:tid 139676073478016] AH00094: Command line: 'httpd -D FOREGROUND'
2017-03-20T18:18:51Z [CFM] resource="ServiceWeb" status="UPDATE_COMPLETE" reason=""
2017-03-20T18:18:56Z [CFM] resource="dev-httpd" status="UPDATE_COMPLETE_CLEANUP_IN_PROGRESS" reason=""
2017-03-20T18:27:30Z web:RXNAPZUJWQP/3fd0ff975e4e 10.0.3.101 - - [20/Mar/2017:18:27:30 +0000] "GET / HTTP/1.1" 200 45
2017-03-20T18:27:30Z web:RXNAPZUJWQP/3fd0ff975e4e 10.0.3.101 - - [20/Mar/2017:18:27:30 +0000] "GET /favicon.ico HTTP/1.1" 404 209
```

**Comment by nzoschke** [comment]
And here's Papertrail for a deploy:

screen shot 2017-03-20 at 12 41 53 pm

**Comment by mwarkentin** [comment]
@nzoschke Neat! Would it make any sense to namespace them so the logs could be filtered in a few different ways?

### All AWS Logs

```
$ convox logs --filter=AWS
2017-03-20T18:07:39Z [AWS-CFM] resource="BalancerWebSecurityGroup" status="CREATE_IN_PROGRESS" reason="Resource creation Initiated"
2017-03-20T18:07:48Z [AWS-CFM] resource="BalancerWeb" status="CREATE_COMPLETE" reason=""
2017-03-20T18:07:54Z [AWS-CFM] resource="ServiceWeb" status="CREATE_IN_PROGRESS" reason="Resource creation Initiated"
2017-03-20T18:08:11Z [AWS-ECS] event="service dev-httpd-ServiceWeb-1274TTQ2F7LR0 has started 1 tasks: task ef76746b-1fcd-4185-a74f-6a4f5a8037ae."
2017-03-20T18:08:11Z [AWS-ECS] service="dev-httpd-ServiceWeb-1274TTQ2F7LR0" task="ef76746b-1fcd-4185-a74f-6a4f5a8037ae" status="PENDING" container="web"
2017-03-20T18:08:12Z [AWS-ECS] service="dev-httpd-ServiceWeb-1274TTQ2F7LR0" task="ef76746b-1fcd-4185-a74f-6a4f5a8037ae" status="RUNNING" container="web"
```

### Cloudformation only

```
$ convox logs --filter=AWS-CFM
2017-03-20T18:07:39Z [AWS-CFM] resource="BalancerWebSecurityGroup" status="CREATE_IN_PROGRESS" reason="Resource creation Initiated"
2017-03-20T18:07:48Z [AWS-CFM] resource="BalancerWeb" status="CREATE_COMPLETE" reason=""
2017-03-20T18:07:54Z [AWS-CFM] resource="ServiceWeb" status="CREATE_IN_PROGRESS" reason="Resource creation Initiated"
```

### ECS only

```
$ convox logs --filter=AWS-ECS
2017-03-20T18:08:11Z [AWS-ECS] event="service dev-httpd-ServiceWeb-1274TTQ2F7LR0 has started 1 tasks: task ef76746b-1fcd-4185-a74f-6a4f5a8037ae."
2017-03-20T18:08:11Z [AWS-ECS] service="dev-httpd-ServiceWeb-1274TTQ2F7LR0" task="ef76746b-1fcd-4185-a74f-6a4f5a8037ae" status="PENDING" container="web"
2017-03-20T18:08:12Z [AWS-ECS] service="dev-httpd-ServiceWeb-1274TTQ2F7LR0" task="ef76746b-1fcd-4185-a74f-6a4f5a8037ae" status="RUNNING" container="web"
```

**Comment by MiguelMoll** [comment]
[Debug agent logging issues](https://trello.com/c/HcI2lkhH/1970-debug-agent-logging-issues)

**Pull request closed without merging**
