### PR TITLE
log cron failures

### PR DESCRIPTION
**Pull request by bobzoller**
### Description
Currently the cron lambda does not check the return value of `ECS.runTask`, which includes a list of `failures` and `tasks`. ([docs](http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html))

This PR checks that return value and logs the reason if it failed, or the task's ARN if it succeeded.

Here's what the app's logstream now looks like when it succeeds:
```
2017-04-21T18:34:48Z run:RVHLXJHJYSJ/cron skew=9588ms command=echo &#39;hello world&#39; result=success task=arn:aws:ecs:us-east-1:811521344363:task/534b07d7-2ad7-4242-8e45-116bfbdf8394
2017-04-21T18:34:50Z agent:0.71/i-08b21cfbc5d807089 Starting run process 0c35e3bd530d
2017-04-21T18:34:51Z run:RVHLXJHJYSJ/0c35e3bd530d hello world
2017-04-21T18:34:51Z agent:0.71/i-08b21cfbc5d807089 Dead run process 0c35e3bd530d
```

and here's what it looks like when it fails:
```
2017-04-21T18:34:22Z run:RVHLXJHJYSJ/cron skew=5739ms command=echo &#39;hello world&#39; result=failure reason=RESOURCE:MEMORY
```

### Summary for release notes
cron log lines include detail about success or failure

### Guidance for reviewers
Manually tested the lambda code, but have been unable to get the go tests to run locally.

### Before Release
- [ ] Rebase against master
- [ ] Get review approval
- [ ] Confirm test coverage
- [ ] Submit documentation PR for convox/site

### CODE REVIEW

**Comment by bobzoller** [comment]
re: my tests not running, I'm being bit by this: https://github.com/golang/go/issues/19734 ... should be able to work around it and get this passing.

**Comment by bobzoller** [comment]
FWIW this local patch got my tests running:

```patch
diff --git a/bin/test b/bin/test
index 9d7839a0..95a517d3 100755
--- a/bin/test
+++ b/bin/test
@@ -2,7 +2,7 @@
 
 set -e
 
-go get -t ./...
+go get -ldflags=-s -t ./...
 
 rm -f coverage.txt
 
@@ -12,16 +12,16 @@ export CLI_TEMPLATE_ERROR_DEBUG=true
 if [ ! -z ${PKG} ]; then
     if [ ! -z ${TEST} ]; then
         echo "Running single test $TEST"
-        go test -coverprofile=profile.out -covermode=atomic "$PKG" -test.run "$TEST"
+        go test -ldflags=-s -coverprofile=profile.out -covermode=atomic "$PKG" -test.run "$TEST"
         exit
     fi
 
-    go test -coverprofile=profile.out -covermode=atomic "$PKG"
+    go test -ldflags=-s -coverprofile=profile.out -covermode=atomic "$PKG"
     exit
 fi
 
 for d in $(find . -not \( -name vendor -prune \) -name '*.go' -exec dirname {} \; | sort -u); do
-  go test -coverprofile=profile.out -covermode=atomic $d
+  go test -ldflags=-s -coverprofile=profile.out -covermode=atomic $d
 
   if [ -f profile.out ]; then
     cat profile.out >> coverage.txt
```

**Comment by bobzoller** [comment]
@mattmanning this resolves one of my commercial support issues

**Comment by MiguelMoll** [comment]
Apologies for the delay. Thanks for the PR. 👍  I'll take a look at this and get it through testing.

**Comment by MiguelMoll** [comment]
Moving the PR forward via #2194 Thanks for this!

**Pull request closed without merging**
