### PR TITLE
add PrivateIP in cli.

### PR DESCRIPTION
**Pull request by ffjia**
We'd like to show EC2 Instance private IP when running `convox instances`, so that we could login to instance via SSH from jump start server.

### CODE REVIEW

**Comment by ddollar** [comment]
Please add two new columns PUBLIC and PRIVATE at the end of the list and I will consider this for merge.

**Comment by ffjia** [comment]
Please review.

**Comment by ddollar** [comment]
Looks good but can you please rebase your commits in this PR to remove the noisy merge commits.

**Comment by ffjia** [comment]
Oops, my apology to push a bunch of unnecessary commits. Please close this request, I created another one #2475.

**Pull request closed without merging**
