### PR TITLE
Memcache

### PR DESCRIPTION
**Pull request by shicholas**
## Release Playbook
- [ ] Rebase against master
- [ ] Release branch ()
- [ ] Pass CI ()
- [ ] Code review
- [ ] Merge into master
- [ ] Release master ()
- [ ] Pass CI ()
- [ ] Update staging rack
- [ ] Edit [Rack release record](https://github.com/convox/rack/releases) and/or update [docs](https://github.com/convox/convox.github.io)
- [ ] Publish release
- [ ] Release CLI

### CODE REVIEW

**Comment by shicholas** [comment]
after compiling the templates I still get an error:

```bash
~/g/s/g/c/rack:memcache> con services create memcache
Creating memcache-2225 (memcache)... ERROR: invalid service type: memcache
```

``con`` is an alias to the local convox I have in my ``$GOPATH/bin``

**Comment by shicholas** [comment]
I guess I'm missing the code that wires up the CLI to using the template, I'm attempting that now by just grepping for where I see redis and creating something similar to memcached.

**Comment by shicholas** [comment]
do I need to run something like ``make release`` (which fails for me) to get the new template to work?

**Comment by nzoschke** [comment]
It looks like you did `make templates` which compiles memcache.tmpl into the API to get picked up by the `CreateDatastore` method.

Did you follow the Development Guide to run a local rack to test these changes? You will need to get some environment from your AWS rack, then `convox start` the rack API on your laptop, then `convox login localhost` to get your CLI talking to that. Then you should have the ability to better test `convox services create memcache`

https://github.com/convox/rack/blob/master/Development.md#local-rack-docker-vm

**Comment by shicholas** [comment]
thanks, I will set it up a local rack. My bad, I thought that I would be testing these changes on my AWS account instead of a rack on a docker-machine on my laptop (I had created a local rack environment but not the VM).

**Comment by shicholas** [comment]
cool, now I'm stuck at this:

```bash
~/g/s/g/c/rack:memcache> con services create memcached
Creating memcached-6149 (memcached)... ERROR: response status: 503
```

you mention [here](https://github.com/convox/rack/pull/670#issuecomment-223642151) to check out the CloudFormation Managemnt Console but I can't seem to find it at https://console.aws.amazon.com/cloudformation/home (checking all 5 filters shown on the console).

Where else should I look for errors?

Thanks so much for your patience with me @nzoschke!

**Comment by nzoschke** [comment]
I would expect the 503 to show up in your local development rack logs. I'll give this a quick test locally and see if I can understand what's going on.

**Comment by nzoschke** [comment]
Here's what I'm seeing:

```bash
$ cd convox/rack
$ go install github.com/convox/rack/cmd/convox
$ convox start
web      | time="2016-06-27T21:22:26Z" level=warning msg="Template format error: Unresolved resource dependencies [NumCacheNodes] in the Resources block of the template" at=service.create count#error.user=1 ns=kernel state=error 
web      | time="2016-06-27T21:22:26Z" level=info msg="completed handling request" count#status4XX=1 measure#web.elapsed=1565.629ms method=POST remote="172.17.0.4:58964" request="/services" status=403 text_status=Forbidden 
```

```
$ convox login localhost
$ convox services create memcached
Creating memcached-8068 (memcached)... ERROR: Template format error: Unresolved resource dependencies [NumCacheNodes] in the Resources block of the template
```

**Comment by ddollar** [comment]
Going to close this for now but happy to revisit if we can get these errors worked out.

**Pull request closed without merging**
