### PR TITLE
Docker Compose and ELB enhancements

### PR DESCRIPTION
**Pull request by nzoschke**
- https://github.com/convox/rack/pull/449 support exec form for command in docker-compose.yml 
- https://github.com/convox/rack/pull/453 Parameterize ELB protocol 
- https://github.com/convox/rack/pull/505 proxy protocol via label
- https://github.com/convox/rack/pull/482 compose v2 support

## Todo:

- [x] Review compose v2 support for manifest model
- [x] Test starting a docker-compose v2 app
- [x] Test deploying a docker-compose v2 app
- [x] Test deploying an app with docker-compose exec format
- [x] Test new ELB parameters against existing app
- [x] Test starting an app with proxy protocol label
- [ ] Test deploying an app with proxy protocol label

## Multi-PR Release Playbook
- [x] Rebase against master
- [x] Pass checks
- [x] Code review
- [x] Merge other PRs into the branch
- [x] Release branch (20160404200737-docker-compose-enhancements)
- [x] Pass CI (https://circleci.com/gh/convox/rack/687)
- [ ] Update dev and testing racks
- [ ] If rack or app formation changes, test upgrade → re-deploy existing app → downgrade cycle
- [ ] Merge into master
- [ ] Master passes checks
- [ ] Release master
- [ ] Pass CI
- [ ] Publish release
- [ ] Release CLI

### CODE REVIEW

**Comment by nzoschke** [comment]
I could use someone to double check all these ELB parameters... 

By default:

```
WebPort80Certificate=<empty>
WebPort80Protocol=<empty> (default TCP)
WebPort80ProxyProtocol=<empty> (default No)

ELB TCP -> Instance TCP
```

```
WebPort80Certificate=<empty>
WebPort80Protocol=<empty> (default TCP)
WebPort80ProxyProtocol=Yes

ELB TCP -> Instance TCP + ProxyProtocol
```

```
WebPort80Certificate=<empty>
WebPort80Protocol=HTTP
WebPort80ProxyProtocol=<empty> (default No)

ELB HTTP -> Instance HTTP
```

I don't think this is valid, need to test...
```
WebPort80Certificate=<empty>
WebPort80Protocol=HTTP
WebPort80ProxyProtocol=Yes

ELB HTTP -> Instance HTTP + Proxy Protocol
```

**Comment by mwarkentin** [comment]
@nzoschke Should this integrate w/ the work in https://github.com/convox/rack/pull/505? Or is that something that can be added in that PR when it's merged?

**Comment by nzoschke** [comment]
@mwarkentin I'm going to bring 505 onto this PR

**Comment by nzoschke** [comment]
v2 tested very well. This deployed no problem:

```
version: '2'
services:
  web:
    image: httpd
    ports:
      - 80:80
```

**Comment by nzoschke** [comment]
Exec format testing... These all work as expected:

Defer to Dockerfile

```
version: '2'
services:
  web:
    image: httpd
    ports:
      - 80:80
```
```
"command": null,
```

exec format:

```
version: '2'
services:
  web:
    image: httpd
    command: ["httpd-foreground"]
    ports:
      - 80:80
```

```
"command": [
  "httpd-foreground"
],
```

sh format:

```
version: '2'
services:
  web:
    image: httpd
    command: "httpd-foreground"
    ports:
      - 80:80
```

```
      "command": [
        "sh",
        "-c",
        "httpd-foreground"
      ],
```

**Comment by nzoschke** [comment]
Redeploying an existing app added the parameter:

```
WebPort80Protocol	TCP
```

but this did not cause any ELB replacement.

**Comment by nzoschke** [comment]
Took a bit of figuring out, but proxy protocol stuff is testing well against nginx.

docker-compose.yml
```
  web:
    build: .
    ports:
      - 81:80
    labels:
      - "com.convox.port.80.protocol=proxy"
```


Dockerfile
```
FROM nginx
COPY nginx.conf /etc/nginx/nginx.conf
```

nginx.conf
```
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format combined '$proxy_protocol_addr - $remote_user [$time_local] '
                        '"$request" $status $body_bytes_sent '
                        '"$http_referer" "$http_user_agent"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80 proxy_protocol;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
}
```

**Comment by mwarkentin** [comment]
@nzoschke Awesome - if you let me know when the updated CLI is released I'll update and test. :smile_cat:

**Comment by nzoschke** [comment]
@mwarkentin just cut the CLI (20160404230648). I'll be doing a bit more testing before publishing this myself.

**Comment by jordansexton** [comment]
I updated to the latest and I'm still running into #449. Is this released yet? I'm probably just confused about how releases are done.

**Comment by jordansexton** [comment]
@nzoschke Do you happen to have any update on the CLI release for this? I'm able to test the rack update but not locally. Is there a way I'm missing to install a specific CLI version, or only installing from source?

**Pull request merged**
