### PR TITLE
add s3-template-url.

### PR DESCRIPTION
**Pull request by ffjia**
Support customized CFN template in user's S3 Bucket, `convox install --stack-name myrack --s3-template-url https://bucket.s3.amazonaws.com/release/20171113014715/formation.json`.

### CODE REVIEW

**Comment by ffjia** [comment]
This is for issue #2332.

**Comment by ddollar** [comment]
This is a good start but will only affect the initial Rack installation. Upgrades past that point would still come from the Convox S3 bucket.

**Comment by ffjia** [comment]
Yep, it won't work when using `convox update`. But as a workaround, you could update the CloudFormation directly, with S3 template url enabled.

I found you guys defined fixed template url of Convox S3 bucket in other places, e.g. in `provider/aws/system.go`, do you think it might be possible to get the URL from convox CLI as well? Hints? Thanksl

**Comment by ddollar** [comment]
Closing this for now. If you want to install Rack from a custom template in an S3 bucket you can do so using the AWS console, CLI, or API. Making all of the convox assets come from an S3 bucket could be interesting but would be a much bigger undertaking.

**Pull request closed without merging**
