### PR TITLE
use stat.Size() alternate instead of seek

### PR DESCRIPTION
**Pull request by MiguelMoll**
Even though os.Stdin is of type io.ReadSeeker, it's illegal to call Seek() on it. This change uses the file's stat size and falls back to ReadSeeker if needed.

This allows for both:
```
> convox builds import < export.tgz
Uploading: 65.19 MB / 65.19 MB [========================] 100.00 % 53s
Importing build... Release: RDGJVQIQXNB
```
and
```
> convox builds export BWJQAAKDFVA | convox builds import
Exporting BWJQAAKDFVA... OK
Release: RETMQURAGRT
```

### CODE REVIEW

**Comment by MiguelMoll** [comment]
Another option would be to load all data into a buffer regardless of type and read the size that way. Seems inefficient but it's an option.

**Comment by ddollar** [comment]
These images can be multiple gigs. The rack process is hard limited to
128MB of RAM

**Comment by MiguelMoll** [comment]
Even being a client side change, can't assume it won't run in a rack so I concur. Any thoughts on the change itself?

**Comment by SonOfBytes** [comment]
I'd advise against in memory. If the concern is lack of feedback then maybe a /-\| (and repeat) spinner every MB to show something is happening?

**Comment by MiguelMoll** [comment]
[Build import/export flakiness](https://trello.com/c/T5v6zHd0/1843-build-import-export-flakiness)

**Pull request closed without merging**
