### PR TITLE
remove cluster instances from load balancers before termination

### PR DESCRIPTION
**Pull request by ddollar**
## Release Playbook
- [x] Rebase against master
- [x] Pass checks
- [ ] Release branch ()
- [ ] Pass CI ()
- [x] Code review
- [ ] Merge into master
- [ ] Release master ()
- [ ] Pass CI ()
- [ ] Update dev and testing racks
- [ ] Publish release
- [ ] Release CLI

### CODE REVIEW

**Comment by bgentry** [comment]
gave this a quick skim, looks solid! Though I feel bad for you guys having to maintain those inlined lambda functions 😨

**Comment by nzoschke** [comment]
Feel bad about us having to write them. It's almost effortless to maintain. :)

**Comment by nzoschke** [comment]
Reviewing this now. Let me see if I got this straight...

* When the ASG begins to terminates an instance, a lifecycle hook is delivered to a Lambda function
* The handler explicitly de-registers the instance from every load balancer
* No matter what after 5 seconds the handler signals to continue the termination
* No matter what after 60 seconds the termination continues

**Comment by nzoschke** [comment]
:+1:

**Pull request merged**
