### PR TITLE
Daemons

### PR DESCRIPTION
**Pull request by nzoschke**
Specify a `convox.daemon` label, and the services will run once on every ECS agent. Uses [ECS CloudWatch Events](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_cwet.html) and Lambda to start daemon on every instance.

```
version: '2'
services:
  agent:
    image: datadog/docker-dd-agent:latest
    environment:
     - API_KEY
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc
      - /cgroup/:/host/sys/fs/cgroup
    privileged: true
    labels:
      - convox.daemon=true
```

### CODE REVIEW

**Comment by mwarkentin** [comment]
Interesting! Eventually maybe the implementation can be swapped out with the native ECS daemon functionality that's being added.

How does this look from a `convox scale` perspective? Will that show you how many processes are running? Is scaling the count of processes disabled for daemons?

**Comment by ddollar** [comment]
Should this be using placement policies like #1504?

**Comment by nzoschke** [comment]
Yes, this should be using placement policies and autoscaling stuff. I'll close this and add the daemon label design proposal to that issue.

**Comment by ddollar** [comment]
Seems like placement isn't the right thing here and this strategy is fine. Seems like just a few Hound violations from being able to ship this?

**Comment by ddollar** [comment]
[Daemon Scheduler](https://trello.com/c/3LNqIY35/1367-daemon-scheduler)

**Comment by ddollar** [comment]
Can reopen with some rebase love.

**Comment by spencerhakim** [comment]
@ddollar I picked this up last night actually, but got distracted when I discovered Docker 1.13 broke `make test`, as the Docker CLI now makes a couple of extra API calls on startup (I'll make a separate issue about this). Anyway, I just need to address the Hound issues and I'll open a PR, if that's cool with @nzoschke.

**Comment by ddollar** [comment]
Please feel free to take this branch and rebase/push it up as a new PR. I think the Docker 1.13 stuff is solved now.

**Pull request closed without merging**
