### PR TITLE
Remove Kinesis from Rack and Apps

### PR DESCRIPTION
**Pull request by nzoschke**
# Removing Kinesis

I'd like to remove Kinesis from all Rack and Apps. CloudWatch Logs is the present and future. If you are using the `papertrail` service or have built custom Kinesis integrations, please read and comment.

We plan to publish this on **Monday, 6/27.** Users can choose not to `convox rack update` to preserve Kinesis.

## History

Very early in the Convox project we picked Kinesis as a service to write log events to. We next wrote a Kinesis to Papertrail adaptor via Lambda. This was a decent log ingestion / tailing / forwarding / storing / searching system.

But eventually we all learned that CloudWatch Logs has far more features:

* A native Docker `awslogs` driver
* Simple sharding. One Log Group has many Log Streams, one per container
* Log archival
* Log filtering
* Log slicing from any start / end point
* Fully integrated in your AWS account for better security, auditing and billing

On [January 20th 2016](https://github.com/convox/rack/pull/269) we introduced writing to CloudWatch Logs. We double wrote logs to both Kinesis and CloudWatch Logs to preserve existing behaviors. Over the next months we worked hard to get the Docker -> CloudWatch Logs pipeline stable.

On [April 18th](https://github.com/convox/rack/releases/tag/20160419004044) we moved `convox logs` to tail, search and filter from CloudWatch Logs.

On [April 20th](https://github.com/convox/rack/releases/tag/20160420221228) we released a `syslog` service that forwards all CloudWatch Logs to arbitrary syslog servers. This is compatible with Papertrail with the added bonus of a more secure TCP + TLS transport.

So now it's time to end the Kinesis experiment. I'd like to:

* Fix some more `syslog` bugs and get everyone happy on the new service
* Release a new convox/agent that stops writing logs to Kinesis
* Remove Kinesis from every Rack and App
* Delete the `papertrail` service
* Consider adding a `kinesis` service if there is still demand to get logs into a Kinesis pipeline

The primary goal is to:

* Save everyone money. We are pushing data through Kinesis that we no longer need to.

The secondary goal is to:

* Simplify Convox. Docker -> awslogs driver -> CloudWatch Logs -> Lambda -> * is clearly the best architecture.

## Actions Required

If you haven't set up any special logging pipelines, no action will be required.

If you do use the `papertrail` service or have integrated Kinesis with other systems, it will require actions:

* Set up Papertrail via the `syslog` service and delete your `papertrail` services
* Migrate any custom Kinesis integrations you set up over to CloudWatch Logs integrations
* Block a future `convox update` until you've removed all subscriptions to the Convox Kinesis streams.

## Timeline

I don't have a specific timeline yet. I do not have visibility into who is using `papertrail` so it's hard to know how disruptive the deprecation could be.

## Release Playbook
- [x] Rebase against master
- [x] Release branch (20160624184041-remove-kinesis)
- [x] Pass CI (https://circleci.com/gh/convox/rack/861)
- [ ] Code review
- [x] Merge into master
- [ ] Release master
- [ ] Pass CI
- [ ] Update dev and testing racks
- [ ] Publish release
- [ ] Release CLI

### CODE REVIEW

**Comment by mwarkentin** [comment]
I believe we've already switched all of our papertrail integrations to syslog, but I'll double-check on that.

**Comment by nzoschke** [comment]
Syslog bugfixes and papertrail deprecation has been released. Had success with our customers in migrating from papertrail to syslog. Going to start testing this PR more seriously.

**Comment by nzoschke** [comment]
Testing update when papertrial is installed:

```
$ convox services create papertrail --url logs4.papertrailapp.com:111111
Creating papertrail-7102 (papertrail: url="logs4.papertrailapp.com:111111")... CREATING

$ convox services link papertrail-7102 --app httpd-old
Linked papertrail-7102 to httpd-old

# link to an app that has kinesis removed
$ convox services link papertrail-7102 --app httpd
ERROR: response status: 500
```

**Comment by nzoschke** [comment]
Updating a rack that removes kinesis when it has a papertrail link cleanly disables the event source in Lambda:

screen shot 2016-06-08 at 5 34 30 pm

**Comment by nzoschke** [comment]
Deleting papertrail service with existing links, disabled or not, works fine.

**Comment by nzoschke** [comment]
convox/agent doesn't try to write to kinesis if a container doesn't have the KINESIS env var set. So its all good for apps / racks with removed kinesis.

**Pull request merged**
