### PR TITLE
move convox switch client side

### PR DESCRIPTION
**Pull request by ddollar**
reads current rack from (in order):

    --rack (not added to commands yet)
    ./.convox/rack
    ~/.convox/rack
    $CONVOX_RACK

`convox switch` now returns the current rack name

`convox switch <rack>` now updates `~/.convox/rack`

## CLI Release Playbook
- [x] Rebase against master
- [x] Release branch (20160617180928-client-switch)
- [x] Pass CI (https://circleci.com/gh/convox/rack/846)
- [x] Code review
- [x] Merge into master
- [ ] Release CLI

### CODE REVIEW

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;FvSfoeDg&#x2F;99-convox-switch"> convox switch</a>

**Comment by nzoschke** [comment]
Testing this... I see some regressions and surprises:

* `convox switch dev-east` no longer works. It requires the personal/ org name prefix
* Switching in another terminal affects the first terminal

```
$ go install github.com/convox/rack/cmd/convox
$ convox login
Logged in successfully.

$ convox switch
Use `convox racks` to list your available racks and `convox switch <rack>` to select one.

$ convox racks
RACK                   STATUS     
convox/staging         running    
convox/demo            running    
convox/production      running    
personal/dev-east      running    

$ convox switch dev-east
ERROR: no such rack: dev-east

$ convox switch personal/dev-east
Switched to personal/dev-east

$ convox apps
APP           STATUS 
httpd         running
```

**Comment by matthewford** [comment]
seems like a fair trade-off to me 😄

**Comment by snario** [comment]
Can't wait for this to be released :+1: :)

**Comment by matthewford** [comment]
This is causing no end of issued for me when we have multiple build running and then deploying from the CLI on CircleCI. 

Sometimes mid deploy the rack will switch so the app will not deploy cleanly (or it will build but not promote the build).

**Comment by nzoschke** [comment]
Picking this up again, and on second review I think it's pretty close as-is

**Comment by nzoschke** [comment]
I think the order of precedence for CONVOX_RACK is incorrect. It should take override ~/.convox/rack as an explicit default for the current terminal session.

**Comment by ddollar** [comment]
+1

**Comment by nzoschke** [comment]
Rebased and changed the precedence. In testing I think that CONVOX_RACK should also override `./.convox/rack` the same way `--rack` would.

This could still use:

- [ ] Adding `--rack` to the help
- [ ] Supporting `convox switch foo` without an org

**Comment by nzoschke** [comment]
## Demo - Switch Command

```bash
$ rm ~/.convox/rack 
$ convox switch
Use `convox racks` to list your available racks and `convox switch <rack>` to select one.

$ convox switch foo
ERROR: Rack not found. Try one of:
convox/staging                    running    
convox/demo                       running    
convox/production                 running    
personal/dev-east                 running    
personal/staging                  running

$ convox switch dev-east
Switched to personal/dev-east

$ convox switch
personal/dev-east

$ convox apps
APP        STATUS 
httpd      running
httpd-old  running
rails      running

$ convox switch staging
ERROR: You have access to multiple racks with that name, try one of the following:
convox/staging
personal/staging

$ convox switch personal/staging
Switched to personal/staging

$ convox switch convox/staging
Switched to convox/staging
```

## Demo - --rack flag

```bash
$ convox apps --help
convox apps: list deployed apps

Usage:
  convox apps <command> [args...]

Subcommands: (convox apps help <subcommand>)
  create  create a new application
  delete  delete an application
  info    see info about an app
  params  list advanced parameters for an app
  help, h 
  
Options:
  --rack value, -r value  Rack name. Inferred from CONVOX_RACK, ./convox/rack or ~/.convox/rack if not specified.
  --help, -h      show help

$ convox switch
convox/staging

$ convox apps
APP              STATUS 
console-staging  running
site-staging     running

$ convox apps --rack dev-east
APP        STATUS 
httpd      running
httpd-old  running
rails      running

$ convox apps -r dev-east
APP        STATUS 
httpd      running
httpd-old  running
rails      running
```

## Demo - CONVOX_RACK env var

```bash
$ convox switch
convox/staging

$ convox apps
APP              STATUS 
console-staging  running
site-staging     running

$ CONVOX_RACK=dev-east convox apps
APP        STATUS 
httpd      running
httpd-old  running
rails      running
```

## Demo -- ./convox/rack file

```bash
$ cd httpd

$ convox switch
convox/staging

$ convox builds
ERROR: no such app: httpd

$ mkdir .convox
$ echo personal/dev-east > .convox/rack

$ convox builds
ID           STATUS    RELEASE      STARTED      ELAPSED  DESC
BVFZQPTJJNV  complete  RTAYZHUSGCJ  1 week ago   22s 

$ convox builds --rack convox/staging
ERROR: no such app: httpd

$ CONVOX_RACK=convox/staging convox builds
ERROR: no such app: httpd
```

**Comment by MiguelMoll** [comment]
I noticed when logging into my local dev rack from Console, `convox switch` is still pointing to a Console rack.

```
⟩ convox switch
convox/demo


⟩ convox login 192.168.99.100
Logged in successfully.


⟩ convox switch
convox/demo


⟩ convox rack
Name     dev
Status   running
Version  20160615213630
Region   us-east-1
Count    3
Type     t2.small
```

**Comment by nzoschke** [comment]
Trying to think about what the `convox login` behavior should be... It could automatically switch to a rack, but it would have to guess which one when logging into console.

**Comment by nzoschke** [comment]
On second thought... I don't think we need to change `convox login` behavior right now. 

I don't think too many people are moving between console and a single rack other than for development. So as long as the behavior is coherent for those of us logged into console its a big improvement.

**Comment by MiguelMoll** [comment]
Latest changes lgtm :+1:

**Comment by nzoschke** [comment]
This needs documentation. A PS1 helper would be very nice too

**Comment by nzoschke** [comment]
Docs are here: https://github.com/convox/site/pull/177

**Pull request merged**
