### PR TITLE
github.com/codegangsta/cli -> gopkg.in/urfave/cli.v1 rename and update

### PR DESCRIPTION
**Pull request by nzoschke**
`github.com/codegangsta/cli` was renamed to `gopkg.in/urfave/cli.v1`, see the Readme:

> Notice: This is the library formally known as github.com/codegangsta/cli -- Github will automatically redirect requests to this repository, but we recommend updating your references for clarity.

This updates the references in convox, and pulls in the latest cli package.

## Release Playbook
- [ ] Rebase against master
- [ ] Release branch ()
- [ ] Pass CI ()
- [ ] Code review
- [ ] Merge into master
- [ ] Release master ()
- [ ] Pass CI ()
- [ ] Update staging rack
- [ ] Edit [Rack release record](https://github.com/convox/rack/releases) and/or update [docs](https://github.com/convox/convox.github.io)
- [ ] Publish release
- [ ] Release CLI

### CODE REVIEW

**Comment by ddollar** [comment]
Looks like you might actually want `gopkg.in/urfave/cli.v1` from the README

**Comment by nzoschke** [comment]
Good catch. Updating again.

**Comment by nzoschke** [comment]
I'm getting this with the newest package:

```
$ convox apps
APP           STATUS 
httpd         running
httpd-old     running
simple-rails  running
DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature
```

Investigating...

**Comment by nzoschke** [comment]
cli Action functions are now supposed to look like

```go
app.Action = func(c *cli.Context) error {
    fmt.Println("boom! I say!")
    return nil
  }
```

Where ours set `Action = cmdApps(c *cli.Context) {}`

**Comment by nzoschke** [comment]
Closing and testing/releasing on #686

**Pull request closed without merging**
